import {test,expect,Page} from '@playwright/test';
const nav=(page:Page,name:string)=>page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name,exact:true});
test.beforeEach(async({page})=>{await page.goto('./');await expect(page.getByRole('navigation',{name:'主导航'})).toBeVisible();});
test('two-step add cancels safely, saves only after confirmation, reload persists',async({page})=>{
 await page.getByRole('button',{name:/记下一件要做的事/}).click();await page.getByRole('textbox',{name:'快速添加标题'}).fill('手机测试任务');await page.getByRole('button',{name:'加入清单',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'安排这件小事'})).toBeVisible();await page.getByRole('button',{name:'计划执行日期',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'安排这件小事'})).toBeVisible();await page.getByRole('button',{name:'取消',exact:true}).click();
 await page.getByRole('button',{name:/记下一件要做的事/}).click();await expect(page.getByRole('textbox',{name:'快速添加标题'})).toHaveValue('手机测试任务');await page.getByRole('button',{name:'加入清单',exact:true}).click();await page.getByRole('button',{name:'确认加入',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.task-main').filter({hasText:'手机测试任务'})).toBeVisible();await page.reload();await expect(page.locator('.task-main').filter({hasText:'手机测试任务'})).toBeVisible();
});
test('task steps, focus collapse/pause/resume, early end and completion records',async({page})=>{
 await page.locator('.task-main').filter({hasText:'给重要的事'}).click();await page.getByRole('button',{name:'编辑',exact:true}).click();await page.getByRole('textbox',{name:'新步骤'}).fill('先写一个小提纲');await page.getByRole('button',{name:'添加步骤',exact:true}).click();await page.getByRole('button',{name:'保存修改'}).click();await page.locator('.task-main').filter({hasText:'给重要的事'}).click();await expect(page.getByText('先写一个小提纲',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'对它开始专注'}).click();await expect(page.getByRole('dialog',{name:'专注时刻'})).toBeVisible();await page.getByRole('button',{name:'返回清单',exact:true}).click();await expect(page.locator('.mini-timer')).toBeVisible();await page.getByRole('button',{name:'暂停计时',exact:true}).click();await expect(page.locator('.mini-timer')).toContainText('已暂停');const value=await page.locator('.mini-timer>strong').innerText();await page.waitForTimeout(1200);await expect(page.locator('.mini-timer>strong')).toHaveText(value);await page.getByRole('button',{name:'继续计时',exact:true}).click();await page.getByRole('button',{name:'恢复专注大屏'}).click();await expect(page.getByRole('dialog',{name:'专注时刻'})).toBeVisible();await page.getByRole('button',{name:'结束本轮',exact:true}).click();await page.getByRole('dialog',{name:'提前结束本轮？'}).getByRole('button',{name:'结束本轮',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await nav(page,'专注').click();await expect(page.locator('.record').first()).toContainText('提前结束');await nav(page,'今天').click();await page.getByRole('button',{name:'完成 给重要的事，留一点专注时间',exact:true}).click();await page.getByRole('button',{name:'全部完成啦！',exact:true}).click();await expect(page.locator('.task-card.done').filter({hasText:'给重要的事'})).toBeVisible();
});
test('time picker keeps draft on cancel and accepts explicit input',async({page})=>{
 await page.locator('.task-main').filter({hasText:'晚一点'}).click();await page.getByRole('button',{name:'编辑',exact:true}).click();const original=await page.getByRole('button',{name:'计划执行时间',exact:true}).innerText();await page.getByRole('button',{name:'计划执行时间',exact:true}).click();await page.getByRole('textbox',{name:'直接输入时间'}).fill('23:59');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'计划执行时间',exact:true})).toHaveText(original);await page.getByRole('button',{name:'计划执行时间',exact:true}).click();await page.getByRole('textbox',{name:'直接输入时间'}).fill('23:59');await page.getByRole('button',{name:'确定',exact:true}).click();await expect(page.getByRole('button',{name:'计划执行时间',exact:true})).toHaveText('23:59');
});
test('stage plan preview and apply; habit completion; trash restore',async({page})=>{
 await nav(page,'清单').click();await page.getByRole('button',{name:'阶段计划',exact:true}).click();await page.getByRole('button',{name:/安排接下来的一小段路/}).click();await page.getByRole('button',{name:'生成排期预览'}).click();await expect(page.getByRole('heading',{name:'预计安排 1 项'})).toBeVisible();await page.getByRole('button',{name:'确认应用安排'}).click();await nav(page,'每日坚持').click();await page.getByRole('button',{name:'这次做到了',exact:true}).first().click();await expect(page.locator('.habit-count').first()).toContainText('1');await nav(page,'清单').click();await page.getByRole('button',{name:'全部',exact:true}).click();await page.locator('.task-main').filter({hasText:'给自己安排一次散步'}).click();await page.getByRole('button',{name:'删除任务',exact:true}).click();await page.getByRole('dialog',{name:'删除这项任务？'}).getByRole('button',{name:'删除任务',exact:true}).click();await nav(page,'设置').click();await page.getByRole('button',{name:/回收站/}).click();await page.getByRole('button',{name:'恢复任务',exact:true}).click();await expect(page.getByText('回收站空空的。')).toBeVisible();
});
test('away screen restores on Esc; reminder acknowledgement creates history',async({page})=>{
 await nav(page,'设置').click();await page.getByRole('button',{name:/暂时离开/}).click();await page.getByRole('button',{name:'吃饭中',exact:true}).click();await expect(page.getByRole('heading',{name:'吃饭中'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:/体验一次提醒/}).click();await expect(page.getByRole('heading',{name:'给自己一个小小的休息'})).toBeVisible();await page.getByRole('button',{name:'我知道了',exact:true}).click();await page.getByRole('button',{name:'提醒中心',exact:true}).click();await expect(page.locator('.record')).toContainText(['给自己一个小小的休息']);
});
for(const width of [360,390,430])test(`six themes, all pages, no overflow at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:844});await nav(page,'设置').click();await page.getByRole('button',{name:/今日心情配色/}).click();const names=['星糖梦境','晴空蜜桃','莓果心动','奶杏布丁','青柠糖球','蜜桃心语'];
 for(const name of names){await page.locator('.theme-card').filter({hasText:name}).click();await expect(page.locator('.theme-card.selected')).toContainText(name);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.keyboard.press('Escape');for(const target of ['今天','清单','每日坚持','专注','设置']){await nav(page,target).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();if(target==='今天')await page.screenshot({path:`artifacts/theme-${name}-${width}.png`});}if(name!==names.at(-1))await page.getByRole('button',{name:/今日心情配色/}).click();}
 await page.reload();await expect(page.locator('.theme-banner')).toContainText('蜜桃心语');
});
test('browser back closes only top selector, then form',async({page})=>{await page.getByRole('button',{name:/记下一件要做的事/}).click();await page.getByRole('textbox',{name:'快速添加标题'}).fill('返回操作');await page.getByRole('button',{name:'加入清单',exact:true}).click();await page.getByRole('button',{name:'优先级',exact:true}).click();await page.goBack();await expect(page.getByRole('dialog',{name:'安排这件小事'})).toBeVisible();await expect(page.getByRole('dialog',{name:'优先级',exact:true})).toHaveCount(0);await page.goBack();await expect(page.getByRole('dialog')).toHaveCount(0);});
test('200% font scaling and long title remain within screen',async({page})=>{await page.evaluate(()=>document.documentElement.style.fontSize='32px');await page.getByRole('button',{name:/记下一件要做的事/}).click();await page.getByRole('textbox',{name:'快速添加标题'}).fill('一个需要分很多小步骤完成的长期任务'.repeat(5));await page.getByRole('button',{name:'加入清单',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'artifacts/large-font-form.png'});});
test('capture actual key pages and first visible focus frame',async({page})=>{await page.screenshot({path:'artifacts/today-final.png'});await page.getByRole('button',{name:/记下一件要做的事/}).click();await page.getByRole('textbox',{name:'快速添加标题'}).fill('把今天的灵感整理成小计划');await page.getByRole('button',{name:'加入清单',exact:true}).click();await page.screenshot({path:'artifacts/task-form-final.png'});await page.keyboard.press('Escape');await nav(page,'专注').click();await page.getByRole('button',{name:'开始专注',exact:true}).click();await expect(page.getByRole('dialog',{name:'专注时刻'})).toBeVisible();await page.screenshot({path:'artifacts/focus-final.png'});await page.getByRole('button',{name:'返回清单',exact:true}).click();await expect(page.locator('.mini-timer')).toBeVisible();await page.screenshot({path:'artifacts/mini-timer-final.png'});});
test('reduced viewport (keyboard simulation) keeps save reachable',async({page})=>{await page.getByRole('button',{name:/记下一件要做的事/}).click();await page.getByRole('textbox',{name:'快速添加标题'}).fill('键盘展开测试');await page.getByRole('button',{name:'加入清单',exact:true}).click();await page.setViewportSize({width:390,height:420});await page.getByRole('textbox',{name:'任务名称'}).focus();await page.getByRole('button',{name:'确认加入'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);});
