import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
Object.assign(globalThis,{TaskDomain:require('../../../src/shared/domain.js'),DiaryV1:require('../../../src/shared/diary-v1.js'),Productivity:require('../../../src/shared/productivity.js'),PreviewRuntime:require('../../../src/shared/runtime.js'),DiarySyncCore:require('../scripts/sync-core.cjs')});
const {seed,personalSeed,apply,newTask}=await import('../src/model');
const {J,newRecord,project,recordChange,materializeRecord,confirmMerge,guardFocusLease}=await import('../src/sync-model');
const task=(title='个人事项')=>({...newTask(),title,scheduleMode:'backlog'});
function change(r:any,c:any){recordChange(r,apply(r.state,c),'test-device');}
test('personal seed has no examples; projection rejects preview',()=>{const s=personalSeed();assert.equal(s.preview,false);assert.equal(s.tasks.length,0);assert.equal(s.habits.length,0);assert.throws(()=>project(seed()),/示例/);assert.throws(()=>apply(s,{type:'reset'}));assert.throws(()=>apply(s,{type:'import',data:{}}));});
test('runtime ticks and local preferences never enter the outbox',()=>{const r=newRecord();change(r,{type:'presence',status:'吃饭中'});change(r,{type:'prefs',patch:{quietEnabled:true}});change(r,{type:'tick'});assert.equal(r.replica.outbox.length,0);});
test('task, steps and theme sync while timer and reminder state stay local',()=>{const r=newRecord(),t={...task(),steps:[{id:'a',title:'步骤',completed:false}]};change(r,{type:'saveTask',task:t});change(r,{type:'theme',id:'bg4'});assert.equal(r.replica.outbox.length,3);assert.equal(r.replica.outbox.find((m:any)=>m.entityType==='step').patch.position,0);assert.equal(r.replica.outbox.find((m:any)=>m.entityType==='preference').patch.themeId,'bg4');assert.ok(!JSON.stringify(r.replica.outbox).includes('nextReminderAt'));});
test('habit completion records immutable events once, not a shared counter',()=>{const r=newRecord();change(r,{type:'saveHabit',habit:{id:'h',title:'喝水',days:[1,2,3],active:false,intervalMinutes:60,scheduleType:'interval'}});change(r,{type:'habitComplete',id:'h'});change(r,{type:'tick'});assert.equal(r.state.habitEvents!.length,1);assert.equal(r.replica.outbox.filter((m:any)=>m.entityType==='habit_event').length,1);assert.equal(r.replica.outbox[0].patch.completionCount,undefined);});
test('first merge previews only deliberate personal edits and saves backup',()=>{const r=newRecord(),guest=newRecord(),t=task();change(guest,{type:'saveTask',task:t});const local=J.materialize(guest.replica),fingerprint=J.fingerprint(local);confirmMerge(r,guest,[],fingerprint,'d');assert.equal(r.state.tasks[0].title,t.title);assert.equal(r.backups!.length,1);assert.equal(r.backups![0].guest!.tasks.length,1);assert.equal(r.replica.migrated,true);assert.equal(guest.state.tasks.length,1);});
test('first merge rejects edits made after preview',()=>{const r=newRecord(),guest=newRecord();const fp=J.fingerprint([]);change(guest,{type:'saveTask',task:task()});assert.throws(()=>confirmMerge(r,guest,[],fp,'d'),/改变/);assert.equal(r.replica.migrated,false);});
test('unmodified defaults do not conflict with an existing cloud theme',()=>{const r=newRecord(),cloud=[{entityType:'preference',entityId:'account',revision:1,payload:{themeId:'bg6'}}];confirmMerge(r,undefined,cloud,J.fingerprint([]),'d');assert.equal(r.state.theme,'bg6');assert.equal(r.replica.outbox.length,0);});
test('cloud tombstones populate recycle bin and explicit restore uses restore operations',()=>{const r=newRecord(),t=task();r.replica.remote={['task|'+t.id]:{entityType:'task',entityId:t.id,payload:t,deletedAt:new Date().toISOString(),revision:2},'step|a':{entityType:'step',entityId:'a',payload:{taskId:t.id,title:'小步骤',completed:false},deletedAt:new Date().toISOString(),revision:2}};materializeRecord(r);assert.equal(r.state.tasks.length,0);assert.equal(r.state.trash[0].task.steps.length,1);change(r,{type:'restore',id:t.id});assert.equal(r.replica.outbox.filter((m:any)=>m.operation==='restore').length,2);});
test('remote download cannot erase edits made while upload is in flight',()=>{const r=newRecord(),t=task();change(r,{type:'saveTask',task:t});const sent=r.replica.outbox[0];sent.attempted=true;change(r,{type:'saveTask',edit:true,task:{...t,title:'上传期间修改'}});assert.equal(r.replica.outbox.length,2);J.commitExchange(r.replica,[{mutationId:sent.mutationId,status:'applied'}],[{entityType:'task',entityId:t.id,payload:t,revision:1}],null);materializeRecord(r);assert.equal(r.state.tasks[0].title,'上传期间修改');assert.equal(r.replica.outbox.length,1);});
test('two offline completions generate the same next occurrence',()=>{const t={...task(),scheduleMode:'day',planDate:'2026-10-07',recurrence:{kind:'daily',interval:1}};const a=newRecord(),b=newRecord();for(const r of [a,b]){change(r,{type:'saveTask',task:t});change(r,{type:'complete',id:t.id,completed:true});}assert.equal(a.state.tasks.find(x=>x.id!==t.id)!.id,b.state.tasks.find(x=>x.id!==t.id)!.id);});

test('persisted focus grant allows one offline completion after wake, not duplicate rounds',()=>{
 const r=newRecord(),now=Date.now();r.state=apply(r.state,{type:'focus',action:'start',minutes:1,mode:'focus'},now);r.focusLease={sessionId:r.state.focusTimer.sessionId,expiresAt:new Date(now+180000).toISOString()};
 assert.equal(guardFocusLease(r,now+3600000),false);r.state=apply(r.state,{type:'tick'},now+3600000);assert.equal(r.state.focusTimer.sessionsCompleted,1);assert.equal(r.state.focusHistory.length,1);r.state=apply(r.state,{type:'tick'},now+3601000);assert.equal(r.state.focusHistory.length,1);
});
test('missing or expired grants pause before settlement and retain unfinished tracking',()=>{
 for(const grant of ['missing','expired']){const r=newRecord(),now=Date.now();r.state=apply(r.state,{type:'focus',action:'start',minutes:1,mode:'focus'},now);if(grant==='expired')r.focusLease={sessionId:r.state.focusTimer.sessionId,expiresAt:new Date(now+20000).toISOString()};
  assert.equal(guardFocusLease(r,now+3600000),true);r.state=apply(r.state,{type:'tick'},now+3600000);assert.equal(r.state.focusTimer.status,'paused');assert.equal(r.state.focusTimer.sessionsCompleted,0);assert.equal(r.state.focusHistory.length,0);assert.ok(r.state.focusTimer.pausedRemainingSeconds>=1);
 }
});
