import React,{useEffect,useRef,useState,useId} from 'react';
import {date} from './model';
// Replacing one sheet with another is not a browser Back action. Synchronize
// after React commits all mounts/unmounts, otherwise a delayed pop closes the new sheet.
const layers=new Map<string,{close:()=>void;level:number}>();
let savedOverflow='',syncQueued=false;
history.replaceState({...history.state,previewLayers:[]},'',location.href);
function syncLayers(){if(syncQueued)return;syncQueued=true;queueMicrotask(()=>{syncQueued=false;const ids=[...layers.keys()],old=history.state?.previewLayers||[];if(ids.length>old.length)history.pushState({...history.state,previewLayers:ids},'',location.href);else history.replaceState({...history.state,previewLayers:ids},'',location.href);if(!ids.length)document.body.style.overflow=savedOverflow;});}
window.addEventListener('popstate',()=>{const expected=history.state?.previewLayers||[];[...layers].sort((a,b)=>b[1].level-a[1].level).forEach(([key,value])=>{if(!expected.includes(key))value.close();});});
export function Icon({name,size=22}:{name:string;size?:number}){const paths:Record<string,React.ReactNode>={
 today:<><rect x="4" y="5" width="16" height="16" rx="5"/><path d="M8 3v4m8-4v4M4 11h16m-12 5 3 3 5-5"/></>,
 list:<><path d="M9 6h11M9 12h11M9 18h11M4 6h.01M4 12h.01M4 18h.01"/></>,
 habit:<><path d="M12 21s-8-5-8-12a4 4 0 0 1 8-2 4 4 0 0 1 8 2c0 7-8 12-8 12Z"/></>,
 focus:<><circle cx="12" cy="13" r="8"/><path d="M9 2h6m-3 7v5l3 2M18 5l2-2"/></>,
 settings:<><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2" fill="currentColor"/><circle cx="16" cy="12" r="2" fill="currentColor"/><circle cx="8" cy="18" r="2" fill="currentColor"/></>,
 search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></>,
 bell:<><path d="M6 9a6 6 0 0 1 12 0c0 7 3 7 3 9H3c0-2 3-2 3-9m4 12h4"/></>,
 plus:<path d="M12 5v14M5 12h14"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,back:<path d="m14 5-7 7 7 7"/>,next:<path d="m10 5 7 7-7 7"/>,down:<path d="m5 9 7 7 7-7"/>,check:<path d="m5 12 5 5L20 7"/>,play:<path d="m8 5 11 7-11 7Z"/>,pause:<path d="M8 5v14M16 5v14"/>,star:<path d="m12 3 3 6 6 1-4 5 1 6-6-3-6 3 1-6-4-5 6-1Z"/>,trash:<><path d="M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/></>,moon:<path d="M19 15A8 8 0 0 1 9 5a8 8 0 1 0 10 10Z"/>,leaf:<path d="M5 19C0 9 13 2 20 3c1 10-6 18-15 16Zm0 0L15 8"/>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.star}</svg>;}
export function Btn({children,kind='',className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{kind?:string}){return <button type="button" className={`btn ${kind} ${className}`} {...props}>{children}</button>;}
export function IconBtn({label,icon,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{label:string;icon:string}){return <button type="button" className="icon-btn" aria-label={label} title={label} {...props}><Icon name={icon}/></button>;}
export function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <div className="field"><span className="field-label">{label}</span>{children}{hint&&<small>{hint}</small>}</div>;}
export function Toggle({label,detail,on,change,disabled=false}:{label:string;detail?:string;on:boolean;change:(v:boolean)=>void;disabled?:boolean}){return <button className="toggle-row" type="button" role="switch" aria-checked={on} disabled={disabled} onClick={()=>change(!on)}><span><b>{label}</b>{detail&&<small>{detail}</small>}</span><span className={`switch ${on?'on':''}`}><i/></span></button>;}
export function Modal({title,children,onClose,full=false,level=0}:{title:string;children:React.ReactNode;onClose:()=>void;full?:boolean;level?:number}){
 const ref=useRef<HTMLDivElement>(null),closeRef=useRef(onClose),uid=useId();closeRef.current=onClose;
 useEffect(()=>{const prior=document.activeElement as HTMLElement;if(!layers.size)savedOverflow=document.body.style.overflow;document.body.style.overflow='hidden';const node=ref.current!;
 layers.set(uid,{close:()=>closeRef.current(),level});syncLayers();
 const focusable=()=>Array.from(node.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),[tabindex="0"]')).filter(n=>n.getClientRects().length);
 const t=setTimeout(()=>{(focusable()[0]||node).focus();},40);
 const top=()=>Array.from(document.querySelectorAll('[data-modal]')).sort((a,b)=>Number((a as HTMLElement).style.zIndex)-Number((b as HTMLElement).style.zIndex)).at(-1)===node;
 const key=(e:KeyboardEvent)=>{if(!top())return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeRef.current();}if(e.key==='Tab'){const fs=focusable(),a=fs[0],z=fs.at(-1);if(e.shiftKey&&document.activeElement===a){e.preventDefault();z?.focus();}else if(!e.shiftKey&&document.activeElement===z){e.preventDefault();a?.focus();}}};
 document.addEventListener('keydown',key,true);
 return()=>{clearTimeout(t);document.removeEventListener('keydown',key,true);layers.delete(uid);syncLayers();prior?.focus();};},[]);
 return <div className={`modal-backdrop ${full?'full':''}`} ref={ref} data-modal role="dialog" aria-modal="true" aria-labelledby={uid} tabIndex={-1} style={{zIndex:100+level*10}}><div className="sheet"><div className="sheet-handle"/><header className="sheet-header"><h2 id={uid}>{title}</h2><IconBtn icon="close" label={`关闭${title}`} onClick={onClose}/></header><div className="sheet-body">{children}</div></div></div>;
}
export function Select({label,value,options,onChange,disabled=false}:{label:string;value:string;options:(string[]|{value:string;label:string;disabled?:boolean})[];onChange:(v:string)=>void;disabled?:boolean}){const [open,setOpen]=useState(false);const opts=options.map(o=>Array.isArray(o)?{value:o[0],label:o[1],disabled:false}:o);return <><button className="select" type="button" aria-label={label} aria-haspopup="dialog" disabled={disabled} onClick={()=>setOpen(true)}><span>{opts.find(o=>o.value===value)?.label||'请选择'}</span><Icon name="down" size={18}/></button>{open&&<Modal title={label} level={4} onClose={()=>setOpen(false)}><div className="option-list">{opts.map(o=><button key={o.value} type="button" disabled={o.disabled} aria-pressed={o.value===value} onClick={()=>{onChange(o.value);setOpen(false);}}><span>{o.label}</span>{o.value===value&&<Icon name="check"/>}</button>)}</div></Modal>}</>;}
export function NumberField({label,value,onChange,min=1,max=1440,unit=''}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;unit?:string}){return <div className="number-field"><button type="button" aria-label={`${label}减少`} disabled={value<=min} onClick={()=>onChange(Math.max(min,value-1))}>−</button><input aria-label={label} type="number" inputMode="numeric" value={value} min={min} max={max} onChange={e=>onChange(Math.max(min,Math.min(max,Number(e.target.value)||min)))}/>{unit&&<span>{unit}</span>}<button type="button" aria-label={`${label}增加`} disabled={value>=max} onClick={()=>onChange(Math.min(max,value+1))}>+</button></div>;}
export function DateField({label,value,onChange,optional=false,min='',max=''}:{label:string;value:string;onChange:(v:string)=>void;optional?:boolean;min?:string;max?:string}){
 const [open,setOpen]=useState(false),[month,setMonth]=useState(()=>new Date(`${value||date()}T12:00:00`));const y=month.getFullYear(),m=month.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();
 return <><button type="button" className="select" aria-label={label} onClick={()=>{setMonth(new Date(`${value||date()}T12:00:00`));setOpen(true);}}><span>{value||'不设置'}</span><Icon name="today" size={20}/></button>{open&&<Modal title={label} level={4} onClose={()=>setOpen(false)}><div className="calendar-nav"><IconBtn label="上个月" icon="back" onClick={()=>setMonth(new Date(y,m-1,1))}/><input aria-label="年份" type="number" min="1900" max="2200" value={y} onChange={e=>{const v=Number(e.target.value);if(v>=1900&&v<=2200)setMonth(new Date(v,m,1));}}/><b>{m+1} 月</b><IconBtn label="下个月" icon="next" onClick={()=>setMonth(new Date(y,m+1,1))}/></div><div className="calendar-grid">{'一二三四五六日'.split('').map(n=><span key={n}>{n}</span>)}{Array.from({length:offset},(_,i)=><span key={`e${i}`}/>)}{Array.from({length:days},(_,i)=>{const d=date(new Date(y,m,i+1));return <button type="button" key={d} className={`${d===value?'selected':''} ${d===date()?'today':''}`} disabled={!!((min&&d<min)||(max&&d>max))} aria-label={d} onClick={()=>{onChange(d);setOpen(false);}}>{i+1}</button>;})}</div><div className="actions"><Btn disabled={!!((min&&date()<min)||(max&&date()>max))} onClick={()=>{onChange(date());setOpen(false);}}>今天</Btn>{optional&&<Btn onClick={()=>{onChange('');setOpen(false);}}>清除日期</Btn>}</div></Modal>}</>;
}
export function TimeField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const [open,setOpen]=useState(false),[draft,setDraft]=useState(value),[error,setError]=useState('');const setPart=(part:number,n:number)=>{const pieces=(/^\d\d:\d\d$/.test(draft)?draft:'09:00').split(':');pieces[part]=String(n).padStart(2,'0');setDraft(pieces.join(':'));};return <><button type="button" className="select" aria-label={label} onClick={()=>{setDraft(value);setError('');setOpen(true);}}><span>{value}</span><Icon name="focus" size={20}/></button>{open&&<Modal title={label} level={4} onClose={()=>setOpen(false)}><p className="muted">24 小时制 · 关闭或取消不会保存</p><input className="time-input" aria-label="直接输入时间" inputMode="numeric" value={draft} maxLength={5} onChange={e=>setDraft(e.target.value)}/><p>小时</p><div className="time-grid">{Array.from({length:24},(_,i)=><button type="button" key={i} className={Number(draft.slice(0,2))===i?'selected':''} onClick={()=>setPart(0,i)}>{String(i).padStart(2,'0')}</button>)}</div><p>分钟</p><div className="time-grid">{Array.from({length:12},(_,i)=><button type="button" key={i} className={Number(draft.slice(3))===i*5?'selected':''} onClick={()=>setPart(1,i*5)}>{String(i*5).padStart(2,'0')}</button>)}</div>{error&&<p role="alert" className="error">{error}</p>}<div className="actions"><Btn onClick={()=>setDraft(new Date().toTimeString().slice(0,5))}>现在</Btn><Btn kind="primary" onClick={()=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(draft)){setError('请填写有效时间，例如 09:30');return;}onChange(draft);setOpen(false);}}>确定</Btn></div></Modal>}</>;}
export function Empty({children}:{children:React.ReactNode}){return <div className="empty"><Icon name="leaf" size={32}/><p>{children}</p></div>;}
