import {useState} from 'react';
import {Btn,Field,Select,DateField,TimeField,NumberField,Toggle,IconBtn,Modal} from './controls';
import {Task,State,clone,date,id,newTask,makePlan} from './model';
type Run=(command:any)=>Promise<boolean>;
export function TaskEditor({initial,isNew,onClose,run,onSaved}:{initial:Task;isNew:boolean;onClose:()=>void;run:Run;onSaved:()=>void}){
 const [t,setT]=useState(()=>clone(initial)),[day,setDay]=useState(initial.dueAt?date(new Date(initial.dueAt)):initial.planDate||date()),[clock,setClock]=useState(initial.dueAt?new Date(initial.dueAt).toTimeString().slice(0,5):new Date().toTimeString().slice(0,5)),[touched,setTouched]=useState(!isNew),[busy,setBusy]=useState(false),[step,setStep]=useState('');
 const patch=(p:Partial<Task>)=>setT(t=>({...t,...p}));
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);try{const when=isNew&&!touched?new Date():new Date(`${day}T${clock}:00`);const value={...t,dueAt:t.scheduleMode==='fixed'?when.toISOString():null,planDate:['day','auto'].includes(t.scheduleMode)?day:null,reminderActive:t.reminderMode!=='none'};if(await run({type:'saveTask',task:value,edit:!isNew})){onSaved();onClose();}}finally{setBusy(false);}}
 const addStep=()=>{if(step.trim()){patch({steps:[...t.steps,{id:id(),title:step.trim(),completed:false}]});setStep('');}};
 return <Modal title={isNew?'安排这件小事':'编辑任务'} full onClose={onClose}><form onSubmit={submit}>
 <Field label="要做的事情"><input aria-label="任务名称" value={t.title} maxLength={120} required onChange={e=>patch({title:e.target.value})}/></Field>
 <Field label="推进方式"><Select label="推进方式" value={t.scheduleMode} options={[["fixed","定时事项"],["day","安排在某一天"],["ongoing","每天持续推进"],["backlog","稍后分配"],["auto","参与智能分配"]]} onChange={v=>{patch({scheduleMode:v});setTouched(true);}}/></Field>
 <div className="form-grid">
 {['fixed','day','auto'].includes(t.scheduleMode)&&<Field label="计划执行日期"><DateField label="计划执行日期" value={day} onChange={v=>{setDay(v);setTouched(true);}}/></Field>}
 {t.scheduleMode==='fixed'&&<Field label="计划执行时间"><TimeField label="计划执行时间" value={clock} onChange={v=>{setClock(v);setTouched(true);}}/></Field>}
 <Field label="优先级"><Select label="优先级" value={t.priority} options={[["normal","普通"],["high","重要"],["low","从容安排"]]} onChange={v=>patch({priority:v})}/></Field>
 <Field label="提醒方式"><Select label="提醒方式" value={t.reminderMode} options={[["none","不单独提醒"],["event","到点 / 提前提醒"],["interval","周期检查"]]} onChange={v=>patch({reminderMode:v})}/></Field>
 </div>
 {t.reminderMode!=='none'&&<div className="soft-box"><Field label={t.reminderMode==='interval'?'每隔多少分钟提醒':'提前多少分钟提醒'}><NumberField label="提醒分钟" min={t.reminderMode==='interval'?1:0} value={t.reminderMinutes} onChange={v=>patch({reminderMinutes:v})} unit="分钟"/></Field><Field label="提醒样式"><Select label="提醒样式" value={t.reminderPresentation} options={[["fullscreen","网页内全屏"],["light","轻提醒卡片"]]} onChange={v=>patch({reminderPresentation:v})}/></Field>{t.reminderMode==='event'&&(t.scheduleMode!=='fixed'?<p className="warning">提前提醒需要选用“定时事项”，并填写执行时间。</p>:new Date(`${day}T${clock}`).getTime()-t.reminderMinutes*60000<=Date.now()&&<p className="warning">提前提醒时刻已过，保存后立即提醒。</p>)}</div>}
 <div className="form-grid"><Field label="最晚截止日期" hint="与计划执行时间分开，可不设置"><DateField label="最晚截止日期" value={t.deadlineDate||''} optional onChange={v=>patch({deadlineDate:v||null})}/></Field>{t.deadlineDate&&<Field label="截止前提醒"><NumberField label="提前提醒天数" min={0} max={365} value={t.deadlineReminderDays} unit="天" onChange={v=>patch({deadlineReminderDays:v})}/></Field>}</div>
 <details className="details" open={!isNew}><summary>补充设置与小步骤</summary><div className="form-grid"><Field label="分类"><input aria-label="分类" maxLength={30} value={t.category} onChange={e=>patch({category:e.target.value})}/></Field><Field label="预计投入"><NumberField label="预计投入" value={t.estimateMinutes} onChange={v=>patch({estimateMinutes:v})} unit="分钟"/></Field></div><Field label="重复任务"><Select label="重复任务" value={t.recurrence.kind} options={[["none","不重复"],["daily","每天"],["weekdays","工作日"],["weekly","每周"],["monthly","每月"]]} onChange={v=>patch({recurrence:{...t.recurrence,kind:v}})}/></Field>{t.recurrence.kind!=='none'&&<Field label="重复间隔"><NumberField label="重复间隔" value={t.recurrence.interval||1} max={365} onChange={v=>patch({recurrence:{...t.recurrence,interval:v}})}/></Field>}
 <Toggle label="纳入阶段计划" detail="明确安排的日期会保留，不被智能排期移动" on={t.inStage!==false} change={v=>patch({inStage:v})}/><Toggle label="紧急提醒" detail="是否穿透勿扰，还受提醒设置控制" on={t.urgentReminder} change={v=>patch({urgentReminder:v})}/>
 <Field label="备注"><textarea aria-label="备注" rows={3} value={t.notes} onChange={e=>patch({notes:e.target.value})}/></Field>
 <h3>小步骤 <small>{t.steps.filter(x=>x.completed).length}/{t.steps.length}</small></h3>{t.steps.map((s,i)=><div className="step-edit" key={s.id}><button type="button" aria-label={`切换步骤 ${s.title}`} className={`check ${s.completed?'checked':''}`} onClick={()=>patch({steps:t.steps.map((x,j)=>j===i?{...x,completed:!x.completed}:x)})}>{s.completed?'✓':''}</button><input aria-label={`步骤${i+1}`} maxLength={120} value={s.title} onChange={e=>patch({steps:t.steps.map((x,j)=>j===i?{...x,title:e.target.value}:x)})}/><IconBtn icon="close" label={`移除步骤${i+1}草稿`} onClick={()=>patch({steps:t.steps.filter((_,j)=>j!==i)})}/></div>)}<div className="inline-input"><input aria-label="新步骤" placeholder="把大任务拆小一点…" maxLength={120} value={step} onChange={e=>setStep(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addStep();}}}/><IconBtn label="添加步骤" icon="plus" onClick={addStep}/></div></details>
 <div className="sticky-actions"><Btn disabled={busy} onClick={onClose}>取消</Btn><Btn kind="primary" type="submit" disabled={busy}>{busy?'正在保存…':isNew?'确认加入':'保存修改'}</Btn></div>
 </form></Modal>;
}
export function HabitEditor({initial,onClose,run}:{initial?:any;onClose:()=>void;run:Run}){
 const [h,setH]=useState(()=>clone(initial||{id:id(),title:'',scheduleType:'interval',intervalMinutes:60,time:'09:00',active:true,days:[0,1,2,3,4,5,6],windowEnabled:false,windowStart:'09:00',windowEnd:'18:00',reminderPresentation:'fullscreen',completionCount:0})),[busy,setBusy]=useState(false);const patch=(p:any)=>setH((h:any)=>({...h,...p}));
 return <Modal title={initial?'编辑每日坚持':'添加每日坚持'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);if(await run({type:'saveHabit',habit:h}))onClose();setBusy(false);}}><Field label="小约定的名字"><input aria-label="坚持名称" placeholder="例如：起来活动一下" required maxLength={80} value={h.title} onChange={e=>patch({title:e.target.value})}/></Field><Field label="提醒规则"><Select label="习惯提醒规则" value={h.scheduleType} options={[["interval","间隔提醒"],["daily","每日定点"]]} onChange={v=>patch({scheduleType:v})}/></Field>{h.scheduleType==='interval'?<Field label="提醒间隔"><NumberField label="习惯提醒间隔" value={h.intervalMinutes} onChange={v=>patch({intervalMinutes:v})} unit="分钟"/></Field>:<Field label="提醒时间"><TimeField label="习惯提醒时间" value={h.time} onChange={v=>patch({time:v})}/></Field>}
 <Field label="在哪些天提醒"><div className="weekdays">{[1,2,3,4,5,6,0].map((d,i)=><button key={d} type="button" className={h.days.includes(d)?'selected':''} aria-pressed={h.days.includes(d)} onClick={()=>patch({days:h.days.includes(d)?h.days.filter((n:number)=>n!==d):[...h.days,d]})}>{'一二三四五六日'[i]}</button>)}</div></Field><Toggle label="仅在指定时段提醒" on={h.windowEnabled} change={v=>patch({windowEnabled:v})}/>{h.windowEnabled&&<div className="form-grid"><Field label="开始时段"><TimeField label="开始时段" value={h.windowStart} onChange={v=>patch({windowStart:v})}/></Field><Field label="结束时段"><TimeField label="结束时段" value={h.windowEnd} onChange={v=>patch({windowEnd:v})}/></Field></div>}<Field label="提醒样式"><Select label="习惯提醒样式" value={h.reminderPresentation} options={[["fullscreen","网页内全屏"],["light","轻提醒卡片"]]} onChange={v=>patch({reminderPresentation:v})}/></Field><Toggle label="启用这个小约定" on={h.active} change={v=>patch({active:v})}/><div className="sticky-actions"><Btn onClick={onClose}>取消</Btn><Btn kind="primary" type="submit" disabled={busy}>保存坚持</Btn></div></form></Modal>;
}
export function StageEditor({s,onClose,run,notice}:{s:State;onClose:()=>void;run:Run;notice:(v:string)=>void}){
 const [stage,setStage]=useState({...s.stage}),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false);const patch=(p:any)=>{setStage({...stage,...p});setResult(null);};
 return <Modal title="阶段计划 · 智能分配" full onClose={onClose}><p className="muted">给长任务留出空间。先看看怎么安排，满意后再确认。</p><div className="form-grid"><Field label="阶段开始"><DateField label="阶段开始" value={stage.start} onChange={v=>patch({start:v})}/></Field><Field label="阶段结束"><DateField label="阶段结束" value={stage.end} min={stage.start} onChange={v=>patch({end:v})}/></Field><Field label="每天任务数"><NumberField label="每天任务数" value={stage.dailyCapacity} max={12} onChange={v=>patch({dailyCapacity:v})}/></Field><Field label="每天可用时间"><NumberField label="每天可用时间" value={stage.dailyMinutes} min={15} unit="分钟" onChange={v=>patch({dailyMinutes:v})}/></Field></div><Toggle label="只安排工作日" on={stage.workdaysOnly} change={v=>patch({workdaysOnly:v})}/><p className="soft-box">已明确日期的任务视为锁定，并计入每日容量；每天持续推进的任务不改期。只分配待安排或参与智能分配的事项。</p><Btn className="wide" kind="primary" onClick={()=>{try{setResult(makePlan(s,stage));}catch(e){notice((e as Error).message);}}}>生成排期预览</Btn>{result&&<section><h3>预计安排 {result.plan.updates.length} 项</h3>{result.plan.updates.map((u:any)=><div className="record" key={u.id}><b>{s.tasks.find(t=>t.id===u.id)?.title}</b><span>{u.planDate||new Date(u.dueAt).toLocaleString('zh-CN')}</span></div>)}{result.plan.conflicts.map((c:any)=><div key={c.id} className="warning">{c.title}：{c.reason}</div>)}{!result.plan.updates.length&&!result.plan.conflicts.length&&<p className="muted">没有需要重新安排的任务；阶段设置仍可保存。</p>}<Btn kind="primary" className="wide" disabled={busy} onClick={async()=>{setBusy(true);if(await run({type:'applyPlan',...result}))onClose();setBusy(false);}}>确认应用安排</Btn></section>}</Modal>;
}
export function createTask(title:string){return {...newTask(),title};}
