import React,{useState,useEffect,useSyncExternalStore,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {initialize,subscribe,getSnapshot,dispatch} from './store';
import {State,Task,date,remaining,timeText,modeLabel,visibleTasks,backup,validateBackup} from './model';
import {D,Diary,P,R} from './rules';
import {themes,themeOf,onSecondary} from './themes';
import {Btn,Icon,IconBtn,Modal,Field,Select,NumberField,TimeField,Toggle,Empty} from './controls';
import {TaskEditor,HabitEditor,StageEditor,createTask} from './editors';
import './style.css';
// CSS custom-property URLs resolve at the consuming stylesheet, not the document.
// Resolve here to keep backgrounds valid when hosted in a project subdirectory.
const assetURL=(file:string)=>new URL('./assets/'+file,location.href).href;
const tabs=[['today','今天','today'],['tasks','清单','list'],['habits','每日坚持','habit'],['focus','专注','focus'],['settings','设置','settings']];
const localTime=(v:string)=>new Date(v).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});
function taskWhen(t:Task){if(t.completed)return '已完成';if(t.scheduleMode==='ongoing')return '每天推进一点';if(t.dueAt)return (new Date(t.dueAt).getTime()<Date.now()?'已到计划时间 · ':'')+localTime(t.dueAt);if(t.planDate)return `${t.planDate} · 灵活安排`;return '还没安排时间';}
function App(){
 const s=useSyncExternalStore(subscribe,getSnapshot),[page,setPage]=useState(location.hash.slice(1)||'today'),[now,setNow]=useState(Date.now()),[panel,setPanel]=useState<any>(null),[toast,setToast]=useState(''),[draft,setDraft]=useState(''),[bigFocus,setBigFocus]=useState(false),[focusTask,setFocusTask]=useState(''),[taskView,setTaskView]=useState('all'),[category,setCategory]=useState(''),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[confirm,setConfirm]=useState<{title:string;detail:string;label?:string;action:()=>Promise<any>}|null>(null),[confirmBusy,setConfirmBusy]=useState(false),[activeKey,setActiveKey]=useState<string|null>(null);
 const theme=themeOf(s.theme),timer=s.focusTimer,active=timer.status!=='idle',seconds=remaining(s,now),busyRef=useRef(false);
 function notice(v:string){setToast(v);}
 async function run(command:any){try{await dispatch(command);return true;}catch(e){notice((e as Error).message||'操作没有保存，请重试');return false;}}
 function navigate(p:string){location.hash=p;setPage(p);window.scrollTo({top:0,behavior:'smooth'});}
 useEffect(()=>{const change=()=>{const next=location.hash.slice(1);if(tabs.some(t=>t[0]===next))setPage(next);};window.addEventListener('hashchange',change);let pending=false;const update=()=>{setNow(Date.now());if(!pending){pending=true;void dispatch({type:'tick'}).catch(e=>notice(e.message)).finally(()=>{pending=false;});}};const tick=setInterval(update,1000);update();return()=>{clearInterval(tick);window.removeEventListener('hashchange',change);};},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{for(const [k,v] of Object.entries(theme))if(['ink','muted','paper','deep','accent','secondary','soft','dark'].includes(k))document.documentElement.style.setProperty(`--${k}`,v);document.documentElement.style.setProperty('--on-secondary',onSecondary(theme));document.documentElement.style.setProperty('--art',`url("${assetURL(`themes/${theme.id}.jpg`)}")`);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme.paper);},[s.theme]);
 useEffect(()=>{if(!active)setBigFocus(false);},[active]);
 useEffect(()=>{setActiveKey(previous=>{const existing=s.pendingReminders.find(r=>r.key===previous);if(existing&&!Diary.deferredReason(s,existing,now))return previous;return R.pickNext(s,now)?.key||null;});},[s,now]);
 const reminder=s.pendingReminders.find(r=>r.key===activeKey),todayTasks=visibleTasks(s,'today'),progress=D.calculateProgress(todayTasks),categories=Array.from(new Set(s.tasks.map(t=>t.category).filter(Boolean)));
 function ask(title:string,detail:string,action:()=>Promise<any>,label='确定'){setConfirm({title,detail,action,label});}
 async function complete(t:Task){const act=async()=>{const okay=await run({type:'complete',id:t.id});if(okay)notice(t.completed?'已恢复到待办清单':getSnapshot().tasks.filter(t=>D.isTaskInView(t,'today',null)&&!t.completed).length?'完成啦！又前进了一小步 ✨':'全部完成啦！今天的你很棒 ✨');};if(!t.completed&&t.steps.some(p=>!p.completed))ask('把小步骤一起完成吗？','这项任务还有未完成的小步骤。确认后，一并标记完成。',act,'全部完成啦！');else await act();}
 async function startFocus(taskId='',mode='focus',minutes?:number){const start=async()=>{if(await run({type:'focus',action:'start',taskId,mode,minutes:minutes||({focus:25,shortBreak:5,longBreak:15} as any)[mode]})){setPanel(null);setBigFocus(true);navigate('focus');}};if(active){if(timer.taskId===taskId&&timer.mode===mode){setBigFocus(true);setPanel(null);}else ask('切换本轮专注？','当前一轮会提前结束，投入时间保留，但不计入完整轮数。',async()=>{if(await run({type:'focus',action:'stop',sessionId:timer.sessionId}))await start();},'结束并切换');}else await start();}
 function stopFocus(){ask('提前结束本轮？','已经投入的时间会保留，未完成的一轮不会增加完成轮数。',async()=>{await run({type:'focus',action:'stop',sessionId:timer.sessionId});},'结束本轮');}
 const openTask=(t:Task)=>setPanel({type:'detail',id:t.id});
 function card(t:Task){return <article className={`task-card ${t.completed?'done':''}`} key={t.id}><button className={`check ${t.completed?'checked':''}`} aria-label={`${t.completed?'恢复':'完成'} ${t.title}`} onClick={()=>void complete(t)}>{t.completed?<Icon name="check" size={17}/>:null}</button><button className="task-main" onClick={()=>openTask(t)}><b>{t.title}</b><span className="task-meta">{t.priority==='high'&&<em>重要</em>}{t.category&&<span>{t.category}</span>}<span>{taskWhen(t)}</span></span>{t.deadlineDate&&!t.completed&&<small className={t.deadlineDate<date(now)?'deadline-danger':'deadline'}>{t.deadlineDate<date(now)?'已超过截止日期':'最晚截止'} {t.deadlineDate}</small>}{t.steps.length>0&&<small>{t.steps.filter(x=>x.completed).length}/{t.steps.length} 小步骤</small>}</button>{!t.completed&&<IconBtn label={`专注 ${t.title}`} icon="play" onClick={()=>void startFocus(t.id)}/>}</article>;}
 const section=(title:string,items:Task[],icon='list')=>items.length>0&&<section className="task-section"><h3><Icon name={icon} size={19}/>{title}<small>{items.length}</small></h3>{items.map(card)}</section>;
 const todayGroups=()=>{const todo=todayTasks.filter(t=>!t.completed),important=todo.filter(t=>t.priorityDate===date(now));const other=todo.filter(t=>!important.includes(t));return <>{section('今日重点',important,'star')}{section('定时事项',other.filter(t=>t.dueAt&&!D.isCarryoverTask(t)), 'bell')}{section('灵活推进',other.filter(t=>!t.dueAt&&!D.isCarryoverTask(t)),'leaf')}{section('之前未完成',other.filter(t=>D.isCarryoverTask(t)),'moon')}{section('已经做到了',todayTasks.filter(t=>t.completed),'check')}{!todo.length&&<div className="celebrate"><h2>全部完成啦！</h2><p>把时间也留一点给自己吧。</p></div>}</>;};
 const detail=panel?.type==='detail'?s.tasks.find(t=>t.id===panel.id):null;
 const todayStart=D.startOfDay(new Date(now)),tomorrow=new Date(todayStart);tomorrow.setDate(tomorrow.getDate()+1);const weekStart=D.startOfWeek(new Date(now)),weekEnd=new Date(weekStart);weekEnd.setDate(weekEnd.getDate()+7);const todayStats=P.summarize(s.focusHistory,timer,todayStart,tomorrow,now),weekStats=P.summarize(s.focusHistory,timer,weekStart,weekEnd,now);
 async function ack(key:string,action:string,minutes=10){if(busyRef.current)return;busyRef.current=true;try{await run({type:'ack',key,action,minutes});}finally{busyRef.current=false;}}
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify(backup(s),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`猫狗日记-示例预览-${date()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('已导出预览数据，不含电脑端正式任务');}
 const timerView=(large=false)=><div className={`timer-view ${large?'large':''}`}><div className="timer-caption">{timer.status==='paused'?'已暂停':active?'正在'+modeLabel(timer.mode):'给自己一段不被打扰的时间'}</div><div className="timer-circle" style={{'--progress':`${active?Math.max(0,Math.min(100,(1-seconds/(timer.durationMinutes*60))*100)):0}%`} as React.CSSProperties}><div><strong>{timeText(seconds)}</strong><span>{modeLabel(timer.mode)} · {timer.durationMinutes} 分钟</span></div></div><h2>{active?(timer.taskTitle||'自由专注'):(s.tasks.find(t=>t.id===focusTask)?.title||'自由专注')}</h2><p className="muted">不用一下完成所有，只专心做好这一刻。</p></div>;
 return <><aside className="desktop-note"><img src="./assets/bear.png" alt="小熊标识"/><p>猫狗日记</p><h1>把大事变小，<br/>把每一步<br/><span>好好记下来。</span></h1><p>手机交互预览 · 示例数据</p><small>浏览器窗口缩窄，即可查看手机布局。<br/>此预览不连接云端，不读取正式任务。</small><div className="desktop-swatches">{themes.map(t=><button key={t.id} style={{background:t.secondary}} title={t.name} aria-label={`切换为${t.name}`} onClick={()=>void run({type:'theme',id:t.id})}/>)}</div></aside>
 <div className={`app-shell ${active?'has-timer':''}`}><div className="preview-strip"><span className="live-dot"/>可点击预览 · 仅示例数据<button onClick={()=>setPanel({type:'about'})}>了解范围</button></div><header className="app-header"><button className="brand" onClick={()=>navigate('today')} aria-label="猫狗日记首页"><img src="./assets/bear.png" alt=""/><span><strong>猫狗日记</strong><small>CAT & DOG DIARY</small></span></button><div className="header-tools"><IconBtn label="搜索任务" icon="search" onClick={()=>{setQuery('');setPanel({type:'search'});}}/><button className="icon-btn" aria-label="提醒中心" onClick={()=>setPanel({type:'reminders'})}><Icon name="bell"/>{s.pendingReminders.length>0&&<span className="badge">{s.pendingReminders.length}</span>}</button></div></header>
 <main>
 {page==='today'&&<><div className="page-kicker">{new Date(now).toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}<span>{theme.name}</span></div><section className="hero"><div className="hero-art"/><div className="hero-content"><span className="eyebrow">A LITTLE BETTER, EVERY DAY</span><h1>今天，也要<br/>慢慢变好呀。</h1><p>{progress.complete===progress.total&&progress.total?'全部完成啦！给自己一颗星。':`还有 ${progress.total-progress.complete} 件小事，陪你一起完成。`}</p><div className="hero-progress"><span style={{width:`${progress.percent}%`}}/></div><small>今日进度 <b>{progress.complete} / {progress.total}</b><em>{progress.percent}%</em></small></div></section><button className="quick-add" onClick={()=>setPanel({type:'add'})}><span><Icon name="plus"/>记下一件要做的事…</span><b>加入清单</b></button>{todayGroups()}</>}
 {page==='tasks'&&<><div className="page-title"><div><span className="eyebrow">ONE THING AT A TIME</span><h1>我的清单</h1></div><IconBtn icon="plus" label="新建任务" onClick={()=>setPanel({type:'add'})}/></div><div className="chips">{[['all','全部'],['week','这一周'],['stage','阶段计划'],['backlog','待安排']].map(([v,n])=><button className={taskView===v?'active':''} key={v} onClick={()=>setTaskView(v)}>{n}</button>)}</div><div className="filter-row"><Select label="分类筛选" value={category} options={[["","全部分类"],...categories.map(x=>[x,x])]} onChange={setCategory}/><Select label="完成状态" value={filter} options={[["all","全部状态"],["todo","未完成"],["done","已完成"]]} onChange={setFilter}/></div>{taskView==='stage'&&<button className="plan-banner" onClick={()=>setPanel({type:'stage'})}><Icon name="today"/><span><b>安排接下来的一小段路</b><small>{s.stage.start} — {s.stage.end}</small></span><Icon name="next"/></button>}<div className="task-section">{visibleTasks(s,taskView,'',category,filter,now).map(card)}{!visibleTasks(s,taskView,'',category,filter,now).length&&<Empty>这里暂时没有事项，给自己一点留白。</Empty>}</div></>}
 {page==='habits'&&<><div className="page-title"><div><span className="eyebrow">SMALL HABITS, BIG CHANGES</span><h1>每日坚持</h1></div><IconBtn icon="plus" label="新增每日坚持" onClick={()=>setPanel({type:'habitEdit'})}/></div><p className="intro">不用很用力，每次做一点就很好。</p>{s.habits.map((h,i)=><article className="habit-card" key={h.id}><div className="habit-heading"><div className="habit-symbol"><Icon name={i%2?'leaf':'sun'} size={28}/></div><div><h2>{h.title}</h2><small>{h.scheduleType==='daily'?`每天 ${h.time}`:`每 ${h.intervalMinutes} 分钟`} · {h.active?'提醒已开启':'提醒已暂停'}</small></div></div><div className="habit-count">已坚持 <strong>{h.completionCount}</strong> 次<span>每一步都算数</span></div><div className="actions"><Btn kind="primary" onClick={async()=>{if(await run({type:'habitComplete',id:h.id}))notice('这次做到了！又积攒了一点点改变 ✨');}}>这次做到了</Btn><Btn onClick={()=>setPanel({type:'habitEdit',habit:h})}>编辑</Btn></div><div className="habit-bottom"><button onClick={()=>void run({type:'habitToggle',id:h.id})}>{h.active?'暂停提醒':'开启提醒'}</button><button onClick={()=>ask('删除这个每日坚持？','删除后不再生成对应提醒，已有提醒记录保留。',async()=>{await run({type:'habitDelete',id:h.id});},'删除')}>删除</button></div></article>)}{!s.habits.length&&<Empty>从喝一杯水这样的约定开始。</Empty>}<p className="footnote">本次只在打开的网页里演示提醒。锁屏或关闭浏览器后，不保证到点弹出。</p></>}
 {page==='focus'&&<><div className="page-title"><div><span className="eyebrow">A MOMENT JUST FOR YOU</span><h1>专注时刻</h1></div><span className="pill">{active?'计时中':'准备开始'}</span></div><div className="mode-tabs">{[['focus','专注'],['shortBreak','短休'],['longBreak','长休']].map(([m,n])=><button key={m} disabled={active} className={timer.mode===m?'active':''} onClick={()=>void run({type:'focus',action:'select',mode:m})}>{n}</button>)}</div>{timerView()}{!active&&<><Field label="这轮想推进什么？"><Select label="关联任务" value={focusTask} options={[["","自由专注"],...s.tasks.filter(t=>!t.completed).map(t=>[t.id,t.title])]} onChange={setFocusTask}/></Field><Field label="自定义时长"><NumberField label="专注时长" value={timer.durationMinutes} max={180} unit="分钟" onChange={v=>void run({type:'focus',action:'select',mode:timer.mode,minutes:v})}/></Field><Btn kind="primary" className="wide" onClick={()=>void startFocus(focusTask,timer.mode,timer.durationMinutes)}><Icon name="play"/>开始{modeLabel(timer.mode)}</Btn></>}{active&&<><div className="actions"><Btn kind="primary" onClick={()=>void run({type:'focus',action:timer.status==='running'?'pause':'start',sessionId:timer.sessionId})}><Icon name={timer.status==='running'?'pause':'play'}/>{timer.status==='running'?'暂停':'继续'}</Btn><Btn onClick={()=>setBigFocus(true)}>打开大屏</Btn></div><Btn className="wide quiet" onClick={stopFocus}>结束本轮</Btn></>}<div className="stats"><div><small>今日专注</small><strong>{Math.floor(todayStats.seconds/60)} <span>分钟</span></strong><small>{todayStats.rounds} 轮完成</small></div><div><small>本周累计</small><strong>{Math.floor(weekStats.seconds/60)} <span>分钟</span></strong><small>{weekStats.rounds} 轮完成</small></div></div><h3>专注足迹</h3>{s.focusHistory.length?s.focusHistory.slice(-10).reverse().map((r:any)=><div className="record" key={r.id}><b>{r.taskTitle}</b><span>{P.formatDuration(r.durationSeconds)} · {r.outcome==='completed'?'完成一轮':'提前结束'}</span><small>{localTime(r.endedAt)}</small></div>):<Empty>第一段专注时光，从现在开始。</Empty>}</>}
 {page==='settings'&&<><div className="page-title"><div><span className="eyebrow">MAKE IT FEEL LIKE YOU</span><h1>我的小天地</h1></div><img className="settings-bear" src="./assets/bear.png" alt="小熊"/></div><button className="theme-banner" onClick={()=>setPanel({type:'themes'})}><img src={`./assets/themes/${s.theme}.jpg`} alt="当前主题背景"/><span><small>今日心情配色</small><b>{theme.name}</b><small>{theme.caption}</small></span><Icon name="next"/></button><div className="settings-group"><h3>提醒与节奏</h3><Toggle label="事项提醒" detail="控制任务和每日坚持；专注完成提醒保留" on={s.preferences.remindersEnabled} change={v=>void run({type:'prefs',patch:{remindersEnabled:v}})}/><Toggle label="勿扰时段" detail="到点提醒会等到勿扰结束后展示" on={s.preferences.quietEnabled} change={v=>void run({type:'prefs',patch:{quietEnabled:v}})}/>{s.preferences.quietEnabled&&<><div className="form-grid"><Field label="勿扰开始"><TimeField label="勿扰开始" value={s.preferences.quietStart} onChange={v=>void run({type:'prefs',patch:{quietStart:v}})}/></Field><Field label="勿扰结束"><TimeField label="勿扰结束" value={s.preferences.quietEnd} onChange={v=>void run({type:'prefs',patch:{quietEnd:v}})}/></Field></div><Toggle label="允许紧急提醒穿透勿扰" on={s.preferences.urgentThroughQuiet} change={v=>void run({type:'prefs',patch:{urgentThroughQuiet:v}})}/></>}<button className="setting-link" onClick={()=>setPanel({type:'notifications'})}><span><b>系统通知与汇总</b><small>能力说明 · 流程演示</small></span><Icon name="next"/></button><button className="setting-link" onClick={()=>setPanel({type:'presence'})}><span><b>暂时离开</b><small>网页内展示离席状态</small></span><Icon name="next"/></button><button className="setting-link" onClick={()=>{setPanel(null);void run({type:'testReminder'});}}><span><b>体验一次提醒</b><small>看看全屏提醒是什么样</small></span><Icon name="play"/></button></div><div className="settings-group"><h3>数据与陪伴</h3>{[['data','示例数据备份','导入、导出与重置'],['trash','回收站',`${s.trash.length} 件示例事项`],['sync','账号与同步','仅流程演示 · 尚未连接'],['about','关于这次预览','功能对照与使用范围']].map(([type,title,desc])=><button className="setting-link" key={type} onClick={()=>setPanel({type})}><span><b>{title}</b><small>{desc}</small></span><Icon name="next"/></button>)}</div><div className="signature"><img src="./assets/bear.png" alt=""/><b>王王碎小熊</b><span>Cat & Dog Diary</span><small>今天也有在认真生活。</small></div></>}
 </main>
 {active&&!bigFocus&&page!=='focus'&&!s.presence.active&&!reminder&&<div className="mini-timer"><button className="mini-label" onClick={()=>navigate('focus')}><Icon name="focus"/><span><b>{timer.taskTitle||'自由专注'}</b><small>{timer.status==='paused'?'已暂停':'专注进行中'}</small></span></button><strong>{timeText(seconds)}</strong><IconBtn label={timer.status==='running'?'暂停计时':'继续计时'} icon={timer.status==='running'?'pause':'play'} onClick={()=>void run({type:'focus',action:timer.status==='running'?'pause':'start',sessionId:timer.sessionId})}/><IconBtn label="恢复专注大屏" icon="next" onClick={()=>setBigFocus(true)}/></div>}
 <nav className="bottom-nav" aria-label="主导航">{tabs.map(([key,name,icon])=><button key={key} className={page===key?'active':''} aria-current={page===key?'page':undefined} onClick={()=>navigate(key)}><span><Icon name={icon}/></span><b>{name}</b></button>)}</nav></div>
 {panel?.type==='add'&&<Modal title="记下一件小事" onClose={()=>setPanel(null)}><p className="muted">先记下来，再慢慢安排。</p><form onSubmit={e=>{e.preventDefault();if(draft.trim())setPanel({type:'taskEdit',isNew:true,task:createTask(draft.trim())});}}><input aria-label="快速添加标题" placeholder="今天想做什么？" maxLength={120} value={draft} onChange={e=>setDraft(e.target.value)} required/><div className="actions"><Btn onClick={()=>setPanel(null)}>先不加了</Btn><Btn kind="primary" type="submit">加入清单</Btn></div></form><small>下一步设置日期、时间、优先级和提醒。确认后才保存。</small></Modal>}
 {panel?.type==='taskEdit'&&<TaskEditor initial={panel.task} isNew={panel.isNew} run={run} onClose={()=>setPanel(null)} onSaved={()=>{if(panel.isNew)setDraft('');notice(panel.isNew?'记下啦！一步一步来。':'修改已保存');}}/>}
 {panel?.type==='detail'&&<Modal title="这一件小事" full onClose={()=>setPanel(null)}>{detail?<><div className="detail-title"><span className="pill">{detail.category||'未分类'}</span><h1>{detail.title}</h1><p>{taskWhen(detail)}</p></div><div className="actions"><Btn kind="primary" disabled={detail.completed} onClick={()=>void startFocus(detail.id)}><Icon name="play"/>对它开始专注</Btn><Btn onClick={()=>setPanel({type:'taskEdit',task:detail,isNew:false})}>编辑</Btn></div><div className="detail-facts"><p><span>优先级</span><b>{{high:'重要',normal:'普通',low:'从容安排'}[detail.priority as 'high']||'普通'}</b></p><p><span>最晚截止</span><b>{detail.deadlineDate||'未设置'}</b></p><p><span>预计投入</span><b>{detail.estimateMinutes} 分钟</b></p><p><span>提醒</span><b>{detail.reminderMode==='none'?'不单独提醒':detail.reminderMode==='interval'?`每 ${detail.reminderMinutes} 分钟`:`提前 ${detail.reminderMinutes} 分钟`}</b></p><p><span>重复</span><b>{{none:'不重复',daily:'每天',weekdays:'工作日',weekly:'每周',monthly:'每月'}[detail.recurrence.kind as 'none']}</b></p></div>{detail.notes&&<p className="notes">{detail.notes}</p>}<h3>拆成小步骤 <small>{detail.steps.filter(p=>p.completed).length}/{detail.steps.length}</small></h3>{detail.steps.map(p=><button className="step-row" key={p.id} onClick={()=>void run({type:'step',id:detail.id,stepId:p.id})}><span className={`check ${p.completed?'checked':''}`}>{p.completed?'✓':''}</span><span>{p.title}</span></button>)}<Btn className="wide quiet" onClick={()=>setPanel({type:'taskEdit',task:detail,isNew:false})}>＋ 添加 / 编辑小步骤</Btn><div className="actions"><Btn onClick={()=>void run({type:'priority',id:detail.id})}><Icon name="star"/>{detail.priorityDate===date(now)?'取消今日重点':'设为今日重点'}</Btn><Btn kind="primary" onClick={()=>void complete(detail)}>{detail.completed?'恢复待办':'完成啦！'}</Btn></div>{detail.reminderActive&&!detail.completed&&<Btn className="wide" onClick={async()=>{if(await run({type:'testReminder',taskId:detail.id}))notice('示例提醒已入队；专注或勿扰期间会暂缓');}}>模拟这项任务的提醒</Btn>}<Btn kind="danger" className="wide quiet" onClick={()=>ask('删除这项任务？','示例任务会移到回收站，可随时恢复。',async()=>{if(await run({type:'delete',id:detail.id}))setPanel(null);},'删除任务')}>删除任务</Btn></>:<Empty>这项任务已经移到回收站。</Empty>}</Modal>}
 {panel?.type==='habitEdit'&&<HabitEditor initial={panel.habit} onClose={()=>setPanel(null)} run={run}/>}
 {panel?.type==='stage'&&<StageEditor s={s} onClose={()=>setPanel(null)} run={run} notice={notice}/>}
 {panel?.type==='search'&&<Modal title="找一件小事" full onClose={()=>setPanel(null)}><input aria-label="搜索内容" placeholder="搜索标题、备注和小步骤" value={query} onChange={e=>setQuery(e.target.value)}/><p className="muted">{query?'在全部任务中搜索':'写下关键词，找回那件事情。'}</p>{query&&visibleTasks(s,'all',query).map(card)}{query&&!visibleTasks(s,'all',query).length&&<Empty>没有找到，换一个关键词试试。</Empty>}</Modal>}
 {panel?.type==='themes'&&<Modal title="换一种好心情" full onClose={()=>setPanel(null)}><p className="muted">六种心情，同样熟悉的小陪伴。</p><div className="theme-grid">{themes.map(t=><button key={t.id} className={`theme-card ${s.theme===t.id?'selected':''}`} aria-pressed={s.theme===t.id} onClick={()=>void run({type:'theme',id:t.id})}><img src={`./assets/themes/${t.id}.jpg`} alt={t.name+'背景'}/><div><b>{t.name}</b><small>{t.caption}</small><span className="swatches">{[t.accent,t.secondary,t.soft].map((c,i)=><i key={i} style={{background:c}}/>)}</span></div>{s.theme===t.id&&<span className="theme-check">✓</span>}</button>)}</div></Modal>}
 {panel?.type==='presence'&&<Modal title="暂时离开一会儿" onClose={()=>setPanel(null)}><p className="muted">只在当前网页内显示，回来后再处理提醒。</p><div className="option-list">{D.PRESENCE_STATUSES.map((v:string)=><button key={v} onClick={()=>{setPanel(null);void run({type:'presence',status:v});}}>{v}<Icon name="next"/></button>)}</div></Modal>}
 {panel?.type==='reminders'&&<Modal title="提醒中心" full onClose={()=>setPanel(null)}><p className="soft-box">预览只在网页打开时检查提醒。不请求系统通知权限，也没有云端推送。</p><Btn className="wide primary" onClick={()=>{setPanel(null);void run({type:'testReminder'});}}>触发一条示例提醒</Btn><h3>等待处理 <small>{s.pendingReminders.length}</small></h3>{s.pendingReminders.map(r=><div className="record" key={r.key}><b>{r.title}</b><small>{Diary.deferredReason(s,r,now)||'等待展示'}</small><div className="actions"><Btn onClick={()=>void ack(r.key,'dismiss')}>我知道了</Btn><Btn onClick={()=>void ack(r.key,'snooze',10)} disabled={r.type==='focus'}>稍后 10 分钟</Btn>{(r.taskId||r.habitId)&&<Btn onClick={()=>void ack(r.key,'complete')}>完成</Btn>}</div></div>)}{!s.pendingReminders.length&&<p className="muted">没有待处理的提醒。</p>}<h3>即将提醒</h3>{[...s.tasks.filter(t=>!t.completed&&t.nextReminderAt),...s.habits.filter(h=>h.active&&h.nextReminderAt)].sort((a,b)=>String(a.nextReminderAt).localeCompare(String(b.nextReminderAt))).map(t=><div className="record" key={t.id}><b>{t.title}</b><span>{localTime(t.nextReminderAt)}</span></div>)}<h3>提醒足迹</h3>{s.reminderHistory.length?s.reminderHistory.slice(-20).reverse().map((r,i)=><div className="record" key={`${r.key}-${i}`}><b>{r.title}</b><span>{{dismiss:'已知晓',complete:'已完成',snooze:'稍后提醒','start-break':'开始休息','start-focus':'开始专注'}[r.action as 'dismiss']||r.action} · {localTime(r.handledAt)}</span></div>):<p className="muted">处理过的提醒会留在这里。</p>}</Modal>}
 {panel?.type==='trash'&&<Modal title="回收站" onClose={()=>setPanel(null)}>{s.trash.length?s.trash.map(x=><div className="record" key={x.task.id}><b>{x.task.title}</b><small>{localTime(x.deletedAt)} 移入</small><Btn onClick={()=>void run({type:'restore',id:x.task.id})}>恢复任务</Btn></div>):<Empty>回收站空空的。</Empty>}</Modal>}
 {panel?.type==='data'&&<Modal title="示例数据备份" onClose={()=>setPanel(null)}><p>这里只处理本次手机预览的数据，不会读取或覆盖电脑端正式任务。</p><Btn className="wide primary" onClick={exportData}>导出示例备份</Btn><label className="btn wide file-button">导入示例备份<input type="file" aria-label="导入示例备份" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>5*1024*1024)throw Error('备份文件超过 5 MB');const data=JSON.parse(await f.text()),validated=validateBackup(data);ask('替换当前预览数据？',`备份包含 ${validated.tasks.length} 个任务、${validated.habits.length} 个每日坚持。建议先导出当前预览。`,async()=>{if(await run({type:'import',data})){setPanel(null);notice('示例备份已导入');}},'导入');}catch(e){notice((e as Error).message);}}}/></label><Btn className="wide danger" onClick={()=>ask('恢复最初的示例？','只重置浏览器中的预览数据，当前修改将被替换。正式任务不受影响。',async()=>{await run({type:'reset'});setPanel(null);},'重置示例')}>重置示例数据</Btn></Modal>}
 {panel?.type==='notifications'&&<Modal title="通知能力 · 演示" onClose={()=>setPanel(null)}><span className="pill">尚未接入系统通知</span><h3>提醒会怎样到达手机？</h3><ol className="explain-list"><li>先将正式网页添加到手机主屏幕。</li><li>正式版再由你主动选择是否允许通知。</li><li>开启后，是否振动、响铃或显示锁屏通知仍由手机系统决定。</li></ol><p>此次预览不请求权限。网页关闭、后台、锁屏时不能保证提醒，更不能保证后台强制全屏。</p><Field label="汇总间隔（流程演示）"><NumberField label="汇总间隔" value={s.preferences.reminderInterval} max={240} unit="分钟" onChange={v=>void run({type:'prefs',patch:{reminderInterval:v}})}/></Field><p className="muted">此处只保存预览选项，不发送汇总系统通知。</p></Modal>}
 {panel?.type==='sync'&&<Modal title="账号与同步 · 演示" onClose={()=>setPanel(null)}><span className="pill">未连接云端</span><h2>把同一份清单，带在身边。</h2><p>正式接入后的流程是：邮箱验证码登录 → 预览本机和云端数据 → 确认合并 → 自动同步。</p><div className="sync-preview"><div><small>本机示例</small><strong>{s.tasks.length} 项任务</strong></div><div><small>云端</small><strong>尚未连接</strong></div></div><Btn className="wide primary" onClick={()=>notice('这是流程预览：尚未接入登录，不需要提供真实邮箱。')}>查看邮箱登录流程</Btn><p className="muted">本次不收集邮箱、密码或密钥，不显示假的同步成功。</p></Modal>}
 {panel?.type==='about'&&<Modal title="这是一份可点击预览" full onClose={()=>setPanel(null)}><img className="about-bear" src="./assets/bear.png" alt="小熊"/><h2>小小清单，大大安心。</h2><p>六套主题沿用电脑端素材。这里的修改仅存于此浏览器；不同浏览器、不同网址和手机之间不会同步。</p><h3>可以实际操作</h3><p>添加与编辑任务、小步骤、重复任务、截止与循环提醒、阶段排期、每日坚持、专注计时与足迹、回收站、主题和示例备份。</p><h3>仅作流程演示</h3><p>邮箱登录、云同步、后台通知与系统汇总。本次不上传任务内容，也不申请通知权限。网站托管方可能记录访问所需的 IP 等基础日志。</p><h3>电脑端专属能力</h3><p>托盘、开机自启、全局快捷键和悬浮小组件不在手机网页提供。切换页面时的迷你计时条只能显示在网页内。</p><h3>手机使用提醒</h3><p>公网内测地址不需要电脑开机，也不用连接同一个 Wi-Fi。可在浏览器菜单中选择“添加到主屏幕”；不同浏览器的名称和支持程度可能不同。添加图标不代表支持后台提醒或离线启动。手机锁屏或离开浏览器可能暂停页面；重新打开时，专注按实际时间恢复。</p></Modal>}
 {bigFocus&&active&&!s.presence.active&&!reminder&&<Modal title="专注时刻" full level={2} onClose={()=>setBigFocus(false)}><div className="focus-screen" style={{'--screen':`url("${assetURL(`screens/${timer.screenId||'screen1'}.jpg`)}")`} as React.CSSProperties}><span className="pill">网页内专注大屏</span>{timerView(true)}<div className="actions"><Btn kind="primary" onClick={()=>void run({type:'focus',action:timer.status==='running'?'pause':'start',sessionId:timer.sessionId})}>{timer.status==='running'?'暂停':'继续'}</Btn><Btn onClick={()=>{setBigFocus(false);navigate('today');}}>返回清单</Btn></div><Btn className="wide quiet" onClick={stopFocus}>结束本轮</Btn><small>关闭或 Esc 只收起，计时不会停止。</small></div></Modal>}
 {s.presence.active&&<Modal title="暂时不在工位" full level={6} onClose={()=>void run({type:'presence'})}><div className="reminder-screen" style={{'--screen':`url("${assetURL(`screens/${s.presence.screenId||'screen1'}.jpg`)}")`} as React.CSSProperties}><img src={`./assets/screens/${s.presence.screenId||'screen1'}.jpg`} alt="离席屏保"/><div className="reminder-copy"><span className="eyebrow">TAKE YOUR TIME</span><h1>{s.presence.status}</h1><p>{localTime(s.presence.startedAt)} 离开</p><p className="muted">提醒已经为你留好，回来再慢慢处理。</p><Btn kind="primary" className="wide" onClick={()=>void run({type:'presence'})}>我回来了</Btn></div></div></Modal>}
 {reminder&&!s.presence.active&&<Modal title={reminder.type==='focus'?'这一轮完成啦':'叮，一件小事'} full={Diary.reminderStyle(s,reminder)==='fullscreen'} level={6} onClose={()=>void ack(reminder.key,'dismiss')}><div className="reminder-screen" style={{'--screen':`url("${assetURL(`screens/${reminder.screenId||'screen1'}.jpg`)}")`} as React.CSSProperties}>{Diary.reminderStyle(s,reminder)==='fullscreen'&&<img src={`./assets/screens/${reminder.screenId||'screen1'}.jpg`} alt="提醒屏保"/>}<div className="reminder-copy"><span className="pill">网页内提醒 · 示例数据</span><h1>{reminder.title}</h1><p>{reminder.subtitle}</p><p className="muted">{reminder.detail}</p><Btn kind="primary" className="wide" onClick={()=>void ack(reminder.key,'dismiss')}>我知道了</Btn>{reminder.type!=='focus'&&<div className="actions"><Btn onClick={()=>void ack(reminder.key,'snooze',10)}>稍后 10 分钟</Btn>{(reminder.taskId||reminder.habitId)&&<Btn onClick={()=>void ack(reminder.key,'complete')}>{reminder.habitId?'这次做到了':'完成任务'}</Btn>}</div>}{reminder.type==='focus'&&<Btn className="wide" onClick={async()=>{await ack(reminder.key,'dismiss');await startFocus('',reminder.mode==='focus'?'shortBreak':'focus');}}>{reminder.mode==='focus'?'开始短休':'开始下一轮'}</Btn>}</div></div></Modal>}
 {confirm&&<Modal title={confirm.title} level={10} onClose={()=>{if(!confirmBusy)setConfirm(null);}}><p>{confirm.detail}</p><div className="actions"><Btn disabled={confirmBusy} onClick={()=>setConfirm(null)}>取消</Btn><Btn kind="primary" disabled={confirmBusy} onClick={async()=>{if(confirmBusy)return;setConfirmBusy(true);try{await confirm.action();setConfirm(null);}catch(e){notice((e as Error).message);}finally{setConfirmBusy(false);}}}>{confirmBusy?'正在处理…':confirm.label}</Btn></div></Modal>}
 {toast&&<div role="status" className="toast" onClick={()=>setToast('')}>{toast}</div>}</>;
}
const root=createRoot(document.getElementById('root')!);
root.render(<div className="startup"><img src="./assets/bear.png" alt="小熊"/><h1>猫狗日记</h1><p>正在打开你的示例小天地…</p></div>);
initialize().then(()=>root.render(<App/>)).catch(error=>root.render(<div className="startup"><h1>预览暂时没能打开</h1><p>{String(error.message||error)}</p><Btn onClick={()=>location.reload()}>重新打开</Btn><p>请使用普通浏览器窗口，而非无痕或文件预览。</p></div>));
