import './src/polyfills';
import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {registerBackgroundSync} from './src/services/background';
import {exportLocalData} from './src/services/export';
import * as Network from 'expo-network';
import {AppState,Image,ImageBackground,Pressable,ScrollView,StyleSheet,Text,View,type ImageSourcePropType} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {ReminderScreen} from './src/reminder-screen';
import {getTheme,THEMES,type ThemeId} from './src/theme/tokens';
import {ThemeContext,Body,Heading,Card,Button,Field,Choices,Sheet,NumberField,DateField} from './src/ui';
import {TaskEditor,HabitEditor} from './src/editors';
import {getAuthState,requestEmailCode,signOut,verifyEmailCode,type AuthState} from './src/services/auth';
import {supabase} from './src/services/supabase';
import {createSupabaseAdapter,SyncService,listConflicts,resolveConflict,deleteCloudAccount,type MergePreview} from './src/services/sync';
import {activeDataset,getMeta,setMeta,newId,listTasks,listHabits,listEntities,saveEntity,deleteEntity,readReplica,localStore,selectAccount,backupReplica,type TaskRecord} from './src/services/local-db';
import {configureNotifications,rebuildReminders,reminderRows,handleReminder,clearDeviceNotifications,openExactAlarmSettings,openNotificationSettings,Notifications,type Reminder} from './src/services/notifications';
import {readFocus,startFocus,toggleFocus,finishFocus,remaining,renewFocusLease,type FocusMode} from './src/services/focus';
const rules=require('../../packages/core/src/mobile-rules');
const diary=require('../../src/shared/diary-v1');
type Tab='today'|'tasks'|'habits'|'focus'|'reminders'|'settings';
const backgrounds:Record<ThemeId,ImageSourcePropType>={bg1:require('./assets/themes/bg1-main.jpg'),bg2:require('./assets/themes/bg2-main.jpg'),bg3:require('./assets/themes/bg3-main.jpg'),bg4:require('./assets/themes/bg4-main.jpg'),bg5:require('./assets/themes/bg5-main.jpg'),bg6:require('./assets/themes/bg6-main.jpg')};
const labels:Record<FocusMode,string>={focus:'自由专注',shortBreak:'短休',longBreak:'长休'};
const errorText=(e:unknown)=>e instanceof Error?e.message:String(e);

export default function App(){
  const [tab,setTab]=useState<Tab>('today'),[themeId,setTheme]=useState<ThemeId>(getMeta('theme.id','bg1'));
  const [tasks,setTasks]=useState<TaskRecord[]>([]),[habits,setHabits]=useState<any[]>([]),[steps,setSteps]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]);
  const [focus,setFocus]=useState(readFocus),[clock,setClock]=useState(Date.now()),[focusMode,setFocusMode]=useState<FocusMode>('focus'),[duration,setDuration]=useState(25);
  const [auth,setAuth]=useState<AuthState>({email:'',signedIn:false,configured:false}),[syncText,setSyncText]=useState('仅保存在本机'),[needsMerge,setNeedsMerge]=useState(!readReplica().migrated),[preview,setPreview]=useState<MergePreview|null>(null),[conflicts,setConflicts]=useState<any[]>([]);
  const [taskDraft,setTaskDraft]=useState<Partial<TaskRecord>|null>(null),[habitDraft,setHabitDraft]=useState<any|null>(null),[detailId,setDetailId]=useState<string|null>(null),[stepTitle,setStepTitle]=useState('');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<{title:string;message:string;action:()=>Promise<void>}|null>(null);
  const [reminders,setReminders]=useState<Reminder[]>(reminderRows),[alert,setAlert]=useState<Reminder|null>(null),[permission,setPermission]=useState('未查询'),[vibrate,setVibrate]=useState(getMeta('notifications.vibrate',true));
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[stage,setStage]=useState<any>({start:rules.day(Date.now()),end:rules.day(Date.now()+21*86400000),dailyCapacity:3,dailyMinutes:120});
  const theme=getTheme(themeId),adapter=useMemo(createSupabaseAdapter,[]),sync=useMemo(()=>adapter?new SyncService(localStore,adapter):null,[adapter]);
  const lastSync=useRef(0),work=useRef(false),authRef=useRef(auth),fullScreenKey=useRef('');authRef.current=auth;
  const contentRef=useRef<ScrollView>(null);
  useEffect(()=>{contentRef.current?.scrollTo({y:0,animated:false});},[tab]);
  const reload=useCallback(async()=>{
    const [ts,hs,ss,hh,pref,plans]=await Promise.all([listTasks(),listHabits(),listEntities('step'),listEntities('focus_session'),listEntities('preference'),listEntities('stage_plan')]);
    setTasks(ts);setHabits(hs);setSteps(ss);setHistory(hh);setFocus(readFocus());setNeedsMerge(!readReplica().migrated);
    if(pref[0]?.themeId){setTheme(getTheme(pref[0].themeId).id);setMeta('theme.id',pref[0].themeId);}if(plans[0])setStage(plans[0]);
    const rows=await rebuildReminders();setReminders(rows);
  },[]);
  const runSync=useCallback(async(manual=false)=>{
    if(!sync||!authRef.current.signedIn||!readReplica().migrated||getMeta('sync.paused',false))return;
    if(!manual&&Date.now()-lastSync.current<3000)return;
    lastSync.current=Date.now();setSyncText('正在同步…');
    try{const result=await sync.run();setSyncText(`已同步 · 待上传 ${readReplica().outbox.length} 条 · ${new Date().toLocaleTimeString()}`);await reload();if(result.conflicts)setConflicts(await listConflicts());}
    catch(e){setSyncText(`待同步 · 修改仍保存在本机：${errorText(e)}`);if(manual)throw e;}
  },[sync,reload]);
  const act=async(action:()=>Promise<void>)=>{if(work.current)return;work.current=true;setBusy(true);try{await action();}catch(e){setError(errorText(e));}finally{work.current=false;setBusy(false);}};
  const changed=async()=>{await reload();void runSync();};
  const loginState=async()=>{const next=await getAuthState();if(next.userId){await clearDeviceNotifications();selectAccount(next.userId);}setAuth(next);authRef.current=next;await reload();if(next.signedIn&&!readReplica().migrated)setSyncText('已登录，请先预览并确认合并。');};
  useEffect(()=>{
    void registerBackgroundSync().catch(e=>setSyncText(`后台同步未启用：${errorText(e)}`));
    void configureNotifications().then(p=>setPermission(p.granted?'已允许':'未允许')).catch(e=>setError(errorText(e)));
    void loginState().then(()=>runSync()).catch(e=>setError(errorText(e)));
    const ticker=setInterval(()=>{setClock(Date.now());const f=readFocus();if(f.running&&remaining(f)===0)void finishFocus().then(()=>reload()).catch(e=>setError(errorText(e)));},1000);
    const polling=setInterval(()=>{void runSync();void rebuildReminders().then(setReminders).catch(e=>setError(errorText(e)));},30000);
    const lease=setInterval(()=>{void renewFocusLease().then(setFocus).catch(e=>{setFocus(readFocus());setSyncText(`专注租约需要联网确认：${errorText(e)}`);});},30000);
    const appState=AppState.addEventListener('change',value=>{if(value==='active'){supabase?.auth.startAutoRefresh();void reload().then(()=>runSync()).catch(e=>setError(errorText(e)));}else supabase?.auth.stopAutoRefresh();});
    const received=Notifications.addNotificationReceivedListener(()=>{void rebuildReminders().then(setReminders).catch(e=>setError(errorText(e)));});
    const showResponse=(r:any)=>{if(r?.notification.request.content.data.dataset===activeDataset()){fullScreenKey.current='';setTab('reminders');void rebuildReminders().then(setReminders).catch(e=>setError(errorText(e)));}};
    const response=Notifications.addNotificationResponseReceivedListener(showResponse);void Notifications.getLastNotificationResponseAsync().then(showResponse);
    const realtime=supabase?.channel('diary-changes').on('postgres_changes',{event:'*',schema:'public',table:'sync_entities'},()=>void runSync()).subscribe();
    const network=Network.addNetworkStateListener(value=>{if(value.isConnected)void runSync();});
    return()=>{clearInterval(ticker);clearInterval(polling);clearInterval(lease);appState.remove();received.remove();response.remove();network.remove();if(realtime)void supabase?.removeChannel(realtime);};
  },[reload,runSync]);
  useEffect(()=>{if(AppState.currentState!=='active'||alert||taskDraft||habitDraft||confirm||detailId||error||preview||conflicts.length)return;const pending=reminders.find(r=>!r.handledAt&&!r.deferred&&Date.parse(r.at)<=clock);if(pending&&pending.key!==fullScreenKey.current){fullScreenKey.current=pending.key;setAlert(pending);}},[clock,reminders,alert,taskDraft,habitDraft,confirm,detailId,error,preview,conflicts]);
  const chooseTheme=async(id:ThemeId)=>{await saveEntity('preference',{themeId:id});setTheme(id);setMeta('theme.id',id);await changed();};
  const saveTask=async(value:any,newSteps:string[])=>{const id=value.id||newId('task');await saveEntity('task',{...value,id,completed:value.completed===true,createdAt:value.createdAt||new Date().toISOString()});for(const [index,title]of newSteps.entries())await saveEntity('step',{id:newId('step'),taskId:id,title,completed:false,position:steps.filter(s=>s.taskId===id).length+index});setTaskDraft(null);await changed();};
  const completeTask=async(task:TaskRecord)=>{const completed=!task.completed;await saveEntity('task',{...task,completed,completedAt:completed?new Date().toISOString():null});if(completed){const state={tasks:[{...task,completed,steps:steps.filter(s=>s.taskId===task.id)}]};const child=diary.spawnNext(state,state.tasks[0],()=>newId('step'));if(child){await saveEntity('task',state.tasks[0]!);await saveEntity('task',child);for(const step of child.steps||[])await saveEntity('step',{...step,taskId:child.id});}}await changed();};
  const beginFocus=async(mode:FocusMode,minutes:number,task?:TaskRecord)=>{const f=await startFocus(mode,minutes,task);setFocus(f);setTab('focus');setDetailId(null);await reload();};
  const handleAlert=async(action:'ack'|'snooze',complete=false)=>{if(!alert)return;const current=reminderRows().find(r=>r.key===alert.key&&r.rule===alert.rule&&r.at===alert.at&&!r.handledAt);if(current){if(complete){if(alert.type==='habit'){await saveEntity('habit_event',{id:`event-${alert.sourceId}-${Date.parse(alert.at)}`,habitId:alert.sourceId,occurredAt:new Date().toISOString(),completed:true,source:'android'});}else{const task=(await listTasks()).find(t=>t.id===alert.sourceId);if(task&&!task.completed)await completeTask(task);}}await handleReminder(alert.key,action,10,alert);}setAlert(null);fullScreenKey.current='';await changed();};
  const detail=tasks.find(t=>t.id===detailId),left=focus.sessionId?remaining(focus,clock):duration*60;
  const visible=(tab==='today'?rules.todayTasks(tasks,clock):tasks).filter((t:TaskRecord)=>filter==='stage'?t.inStage!==false:filter==='backlog'?t.scheduleMode==='backlog':filter==='done'?t.completed:filter==='open'?!t.completed:true).filter((t:TaskRecord)=>`${t.title} ${t.notes||''} ${t.category||''}`.toLowerCase().includes(query.toLowerCase()));
  const ask=(title:string,message:string,action:()=>Promise<void>)=>setConfirm({title,message,action});
  return <SafeAreaProvider><ThemeContext.Provider value={theme}><ImageBackground source={backgrounds[theme.id]} resizeMode="cover" style={styles.fill} imageStyle={{opacity:0.2}}><SafeAreaView style={[styles.fill,{backgroundColor:`${theme.colors.canvas}DE`}]}><View style={styles.header}><Image source={require('./assets/icon.png')} style={{width:42,height:42}}/><View><Text style={[styles.brand,{color:theme.colors.ink}]}>猫狗日记</Text><Text style={{color:theme.colors.muted,fontSize:11,letterSpacing:1.5}}>CAT & DOG DIARY</Text></View><Text style={{color:theme.colors.muted,marginLeft:'auto',fontSize:12}}>{auth.signedIn?`待同步 ${readReplica().outbox.length}`:'本地优先'}</Text></View>
    <ScrollView ref={contentRef} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>
      {(tab==='today'||tab==='tasks')&&<><Heading>{tab==='today'?'今天，专心做好一件事。':'事情都在这里'}</Heading><Body muted>{rules.day(clock)} · 有安排，也留一点余地。</Body><Button title="＋ 记下一件事" onPress={()=>setTaskDraft({scheduleMode:tab==='tasks'&&filter==='stage'?'backlog':'fixed',inStage:true})}/>{tab==='tasks'&&<Choices label="查看" value={filter} onChange={setFilter} options={[["all","全部"],["open","未完成"],["stage","阶段计划"],["backlog","待安排"],["done","已完成"]]}/>}<Field label="搜索任务与备注" value={query} onChange={setQuery} placeholder="输入关键词"/>{tab==='tasks'&&filter==='stage'&&<Card><Heading>规划这段时间</Heading><DateField label="阶段开始" value={stage.start} onChange={v=>setStage({...stage,start:v})} optional={false}/><DateField label="阶段结束" value={stage.end} onChange={v=>setStage({...stage,end:v})} optional={false}/><NumberField label="每天最多任务数" value={stage.dailyCapacity} onChange={v=>setStage({...stage,dailyCapacity:v})} max={12}/><NumberField label="每天可投入分钟" value={stage.dailyMinutes} onChange={v=>setStage({...stage,dailyMinutes:v})} max={1440}/><Button title="预览智能排期" onPress={()=>void act(async()=>{const result=diary.plan(tasks,stage);ask('应用这次排期？',`将安排 ${result.updates.length} 项；未安排 ${result.conflicts?.length||0} 项。手动锁定的日期保留。`,async()=>{await saveEntity('stage_plan',stage);for(const update of result.updates){const t=tasks.find(t=>t.id===update.id);if(t)await saveEntity('task',{...t,...update});}await changed();});})}/></Card>}{visible.length===0&&<Card><Heading>此刻，全部完成啦！</Heading><Body muted>也可以先记下来，稍后再安排。</Body></Card>}{visible.map((task:TaskRecord)=><Card key={task.id}><View style={styles.row}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:task.completed}} accessibilityLabel={`完成 ${task.title}`} disabled={busy} onPress={()=>void act(()=>completeTask(task))} style={[styles.check,{backgroundColor:task.completed?theme.colors.accent:theme.colors.canvas,borderColor:theme.colors.border}]}><Text style={{color:theme.colors.ink,fontSize:21}}>{task.completed?'✓':''}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>setDetailId(task.id)} style={{flex:1}}><Text style={{color:theme.colors.ink,fontSize:18,fontWeight:'800',textDecorationLine:task.completed?'line-through':'none'}}>{task.title}</Text><Body muted>{task.scheduleMode==='ongoing'?'每天持续推进':task.dueAt?new Date(task.dueAt).toLocaleString():task.planDate||'稍后安排'}</Body>{!!task.deadlineDate&&<Body>最晚 {task.deadlineDate} · 提前 {task.deadlineReminderDays??3} 天提醒</Body>}</Pressable></View></Card>)}</>}
      {tab==='habits'&&<><Heading>每日坚持</Heading><Body muted>小事重复，慢慢变成你的节奏。</Body><Button title="＋ 添加每日坚持" onPress={()=>setHabitDraft({})}/>{habits.length===0&&<Card><Body>还没有坚持事项，添加第一个吧。</Body></Card>}{habits.map(h=><Card key={h.id}><Heading>{h.icon||'✦'} {h.title}</Heading><Body muted>{h.scheduleType==='daily'?`每天 ${h.time}`:`每 ${h.intervalMinutes} 分钟`} · {h.active===false?'已暂停':'提醒开启'}</Body><Button title="这次做到了 ✓" disabled={busy} onPress={()=>void act(async()=>{await saveEntity('habit_event',{id:newId('habit-event'),habitId:h.id,occurredAt:new Date().toISOString(),completed:true,source:'android'});await handleReminder(`habit:${h.id}`,'ack');await changed();})}/><View style={styles.row}><Button secondary title={h.active===false?'开启提醒':'暂停提醒'} onPress={()=>void act(async()=>{await saveEntity('habit',{...h,active:h.active===false});await changed();})}/><Button secondary title="修改" onPress={()=>setHabitDraft(h)}/><Button secondary danger title="删除" onPress={()=>ask('删除这项坚持？','已完成记录会保留。',async()=>{await deleteEntity('habit',h.id);await changed();})}/></View></Card>)}</>}
      {tab==='focus'&&<><Heading>{focus.sessionId&&!focus.completed?focus.taskTitle||labels[focus.mode]:'留一点时间给重要的事'}</Heading><Card><Text style={{fontSize:76,fontWeight:'900',color:theme.colors.ink,textAlign:'center',fontVariant:['tabular-nums'],paddingVertical:24}}>{String(Math.floor(left/60)).padStart(2,'0')}:{String(left%60).padStart(2,'0')}</Text><Body>{focus.sessionId&&!focus.completed?(focus.running?'正在进行':'已暂停'):focus.completed?'这一轮完成啦！':'准备开始'}</Body>{!focus.sessionId||focus.completed?<><Choices label="模式" value={focusMode} onChange={v=>{setFocusMode(v as FocusMode);setDuration(v==='focus'?25:v==='shortBreak'?5:15);}} options={[["focus","专注"],["shortBreak","短休"],["longBreak","长休"]]}/><NumberField label="时长（分钟）" value={duration} onChange={setDuration}/><Button title="开始这一轮" disabled={busy} onPress={()=>void act(()=>beginFocus(focusMode,duration))}/></>:<><Button title={focus.running?'暂停':'继续'} disabled={busy} onPress={()=>void act(async()=>{setFocus(await toggleFocus());await reload();})}/><Button secondary title="结束本轮" onPress={()=>ask('结束这一轮？','未完成的本轮不计入完成轮数，已投入时间仍会保留。',async()=>{setFocus(await finishFocus(true));await changed();})}/></>}<Body muted>切换页面或锁屏后按现实时间继续计时；到点提醒只产生一次。</Body></Card><Heading>最近专注记录</Heading>{history.slice().sort((a,b)=>b.endedAt.localeCompare(a.endedAt)).slice(0,20).map(h=><Card key={h.id}><Body>{h.taskTitle||'自由专注'} · {Math.round(h.durationSeconds/60)} 分钟</Body><Body muted>{new Date(h.endedAt).toLocaleString()} · {h.outcome==='completed'?'已完成':'提前结束'}</Body></Card>)}</>}
      {tab==='reminders'&&<><Heading>提醒中心</Heading><Body muted>未处理的循环提醒只保留一条，处理后重新计时。</Body>{reminders.filter(r=>!r.handledAt).map(r=><Card key={r.key}><Heading>{r.title}</Heading><Body muted>{r.deferred?'专注结束后提醒':new Date(r.at).toLocaleString()}</Body><Button title={Date.parse(r.at)<=clock?'查看提醒':'稍后处理'} secondary onPress={()=>setAlert(r)}/></Card>)}{!reminders.some(r=>!r.handledAt)&&<Card><Body>暂时没有待处理提醒。</Body></Card>}</>}
      {tab==='settings'&&<><Heading>设置与同步</Heading><Choices label="选择主题" value={theme.id} onChange={id=>void act(()=>chooseTheme(id as ThemeId))} options={Object.values(THEMES).map(t=>[t.id,t.name])}/><Card><Heading>手机提醒</Heading><Body>通知权限：{permission}</Body><Button title="允许醒目通知" onPress={()=>void act(async()=>{const p=await configureNotifications(true);setPermission(p.granted?'已允许':'被系统拒绝');await reload();})}/><Button secondary title={vibrate?'震动：开启':'震动：关闭'} onPress={()=>void act(async()=>{setMeta('notifications.vibrate',!vibrate);setVibrate(!vibrate);await clearDeviceNotifications();const rows=reminderRows().map(r=>({...r,notificationId:null,scheduledAt:null}));setMeta(`reminders.${activeDataset()}`,rows);await reload();})}/><Button secondary title="闹钟和提醒权限" onPress={()=>void act(openExactAlarmSettings)}/><Button secondary title="系统通知与省电设置" onPress={()=>void act(openNotificationSettings)}/><Body muted>后台使用高优先级通知、震动和锁屏提示；前台显示主题提醒。系统强制停止或厂商省电限制可能延迟提醒，不保证后台强制全屏。</Body></Card><SyncPanel auth={auth} syncText={syncText} needsMerge={needsMerge} onLogin={loginState} busy={busy} act={act} onSync={()=>runSync(true)} onPreview={async()=>{if(!sync)throw Error('未配置云端');setPreview(await sync.preview());}} onConflicts={async()=>setConflicts(await listConflicts())} onLogout={async()=>{await signOut();setAuth(await getAuthState());authRef.current=await getAuthState();setSyncText('已退出，本机数据保留');}} onDelete={()=>ask('删除云端账号？','云端任务、习惯、专注记录和设备会话将永久删除。本机数据保留，重新注册后需要再次确认合并。',async()=>{backupReplica('before-account-delete');await deleteCloudAccount();setAuth(await getAuthState());authRef.current=await getAuthState();await reload();})}/><Button secondary title="导出本机数据" onPress={()=>void act(async()=>{await exportLocalData();})}/><Body muted>Android 内测版 0.1.1 · 不包含真实云端配置时可离线使用。账号数据只同步到你配置的 Supabase 项目。</Body></>}
    </ScrollView><View style={[styles.tabs,{backgroundColor:theme.colors.surface,borderTopColor:theme.colors.border}]}>{([['today','今天'],['tasks','清单'],['habits','坚持'],['focus','专注'],['reminders','提醒'],['settings','设置']]as const).map(([id,label])=><Pressable key={id} accessibilityRole="tab" accessibilityState={{selected:tab===id}} onPress={()=>{setTab(id);setFilter('all');}} style={[styles.tab,{backgroundColor:tab===id?theme.colors.accent:'transparent'}]}><Text style={{color:theme.colors.ink,fontSize:14,fontWeight:'700'}}>{label}</Text></Pressable>)}</View>
    <Sheet visible={taskDraft!==null} title={taskDraft?.id?'修改任务':'安排下一步'} onClose={()=>setTaskDraft(null)}>{taskDraft&&<TaskEditor key={taskDraft.id||'new'} task={taskDraft} onSave={saveTask}/>}</Sheet>
    <Sheet visible={habitDraft!==null} title="每日坚持" onClose={()=>setHabitDraft(null)}>{habitDraft&&<HabitEditor key={habitDraft.id||'new'} habit={habitDraft} onSave={async h=>{await saveEntity('habit',{...h,id:h.id||newId('habit')});setHabitDraft(null);await changed();}}/>}</Sheet>
    <Sheet visible={!!detail} title={detail?.title||'任务详情'} onClose={()=>setDetailId(null)}>{detail&&<><Body>{detail.notes||'还没有备注'}</Body><Button title="对这件事开始专注" disabled={busy} onPress={()=>void act(()=>beginFocus('focus',25,detail))}/><Button secondary title="编辑计划与提醒" onPress={()=>{setTaskDraft(detail);setDetailId(null);}}/><Heading>小步骤</Heading>{steps.filter(s=>s.taskId===detail.id).sort((a,b)=>(a.position||0)-(b.position||0)).map(step=><View key={step.id} style={styles.row}><Button secondary title={`${step.completed?'✓':'○'} ${step.title}`} onPress={()=>void act(async()=>{await saveEntity('step',{...step,completed:!step.completed,completedAt:!step.completed?new Date().toISOString():null});await changed();})}/><Button secondary danger title="×" onPress={()=>ask('删除这个小步骤？',step.title,async()=>{await deleteEntity('step',step.id);await changed();})}/></View>)}<Field label="新小步骤" value={stepTitle} onChange={setStepTitle}/><Button secondary title="添加步骤" onPress={()=>void act(async()=>{if(!stepTitle.trim())throw Error('请填写小步骤');await saveEntity('step',{id:newId('step'),taskId:detail.id,title:stepTitle.trim(),completed:false,position:steps.filter(s=>s.taskId===detail.id).length});setStepTitle('');await changed();})}/><Button danger secondary title="删除任务" onPress={()=>ask('删除这件事？','会同步删除任务和小步骤。旧设备的修改不会让它重新出现。',async()=>{if(readFocus().taskId===detail.id&&!readFocus().completed)await finishFocus(true);await deleteEntity('task',detail.id);setDetailId(null);await changed();})}/></>}</Sheet>
    <Sheet visible={!!preview} title="首次同步预览" onClose={()=>setPreview(null)}>{preview&&<><Body>本机 {preview.localEntities} 条，云端 {preview.cloudEntities} 条。</Body><Body muted>确认前不上传、不替换数据。确认后先保存本地备份，再合并双方独有内容。同字段的不同修改会留到冲突中心选择，已删除的记录不会自动复活。</Body><Button title="备份并合并" disabled={busy} onPress={()=>void act(async()=>{await sync!.merge(preview.token);setPreview(null);setNeedsMerge(false);await reload();await runSync(true);})}/><Button secondary title="取消" onPress={()=>setPreview(null)}/></>}</Sheet>
    <Sheet visible={!!conflicts.length} title="选择保留的修改" onClose={()=>setConflicts([])}>{conflicts.map(c=><ConflictCard key={c.conflict_id} conflict={c} onResolve={resolution=>void act(async()=>{await resolveConflict(c,resolution);setConflicts(await listConflicts());await runSync(true);})}/>)}</Sheet>
    <Sheet visible={!!confirm} title={confirm?.title||'请确认'} onClose={()=>setConfirm(null)}><Body>{confirm?.message}</Body><Button secondary title="取消" onPress={()=>setConfirm(null)}/><Button title="确认" disabled={busy} onPress={()=>void act(async()=>{await confirm!.action();setConfirm(null);})}/></Sheet>
    <Sheet visible={!!error} title="这一步没有完成" onClose={()=>setError('')}><Body>{error}</Body><Body muted>本机内容仍保留，可以调整后重试。</Body><Button title="知道了" onPress={()=>setError('')}/></Sheet>
    <ReminderScreen reminder={alert} busy={busy} onAction={(action,complete)=>void act(()=>handleAlert(action,complete))}/>
  </SafeAreaView></ImageBackground></ThemeContext.Provider></SafeAreaProvider>;
}

function SyncPanel({auth,syncText,needsMerge,onLogin,busy,act,onSync,onPreview,onConflicts,onLogout,onDelete}: {auth:AuthState;syncText:string;needsMerge:boolean;onLogin:()=>Promise<void>;busy:boolean;act:(fn:()=>Promise<void>)=>Promise<void>;onSync:()=>Promise<void>;onPreview:()=>Promise<void>;onConflicts:()=>Promise<void>;onLogout:()=>Promise<void>;onDelete:()=>void}){
  const [email,setEmail]=useState(auth.email),[code,setCode]=useState(''),[sent,setSent]=useState(false),[paused,setPaused]=useState(getMeta('sync.paused',false));
  if(!auth.configured)return <Card><Heading>离线内测</Heading><Body>无需注册或登录。任务、每日坚持和专注记录都保存在这台手机。</Body><Body muted>这一版暂不连接云端，也不会向电脑自动同步。请定期使用下方“导出本机数据”备份；卸载前务必导出。后续启用同步时会先预览并确认合并，不会直接覆盖资料。</Body></Card>;
  return <Card><Heading>跨设备同步</Heading><Body muted>{auth.configured?syncText:'尚未配置 Supabase；不影响本机使用。配置方法见内测说明。'}</Body>{!auth.signedIn?<><Field label="邮箱" value={email} onChange={setEmail} placeholder="name@example.com"/><Field label="邮箱验证码" value={code} onChange={setCode} numeric/><Button secondary disabled={busy||!auth.configured} title={sent?'重新发送验证码':'发送验证码'} onPress={()=>void act(async()=>{await requestEmailCode(email);setSent(true);})}/>{sent&&<Body muted>请检查邮箱与垃圾邮件。没有验证码时，请管理员检查 Supabase 邮件模板。</Body>}<Button title="验证并登录" disabled={busy||!auth.configured} onPress={()=>void act(async()=>{await verifyEmailCode(email,code);await onLogin();})}/></>:<><Body>{auth.email}</Body><Button title={needsMerge?'预览首次同步':'立即同步'} disabled={busy||paused} onPress={()=>void act(needsMerge?onPreview:onSync)}/><Button secondary title={paused?'恢复自动同步':'暂停自动同步'} onPress={()=>{setMeta('sync.paused',!paused);setPaused(!paused);}}/><Button secondary title="查看同步冲突" onPress={()=>void act(onConflicts)}/><Button secondary title="退出账号（保留本机数据）" onPress={()=>void act(onLogout)}/><Button secondary danger title="删除云端账号" onPress={onDelete}/></>}</Card>;
}
function ConflictCard({conflict:c,onResolve}: {conflict:any;onResolve:(value:Record<string,unknown>)=>void}){
  const [choices,setChoices]=useState<Record<string,string>>({});const deletion=c.conflict_fields.includes('deletedAt');
  return <Card><Heading>{c.local_patch.title||c.remote_payload.title||c.entity_id}</Heading>{deletion?<><Body>本机操作与云端状态冲突。可以保留云端状态，或明确执行下方操作。</Body><Button secondary title="保留云端状态" onPress={()=>onResolve({action:'keepRemote'})}/><Button title={c.remote_deleted_at?"明确恢复此记录":"确认删除此记录"} onPress={()=>onResolve({action:c.remote_deleted_at?'restore':'delete',fields:c.local_patch})}/></>:<>{c.conflict_fields.map((field:string)=><Choices key={field} label={field} value={choices[field]||''} onChange={v=>setChoices({...choices,[field]:v})} options={[["local",`本机：${JSON.stringify(c.local_patch[field]??null)}`],["remote",`云端：${JSON.stringify(c.remote_payload[field]??null)}`]]}/>)}<Button title="确认全部选择" disabled={c.conflict_fields.some((f:string)=>!choices[f])} onPress={()=>onResolve({action:'merge',fields:Object.fromEntries(c.conflict_fields.map((f:string)=>[f,(choices[f]==='local'?c.local_patch:c.remote_payload)[f]??null]))})}/><Button secondary title="全部保留云端" onPress={()=>onResolve({action:'keepRemote'})}/></>}</Card>;
}
const styles=StyleSheet.create({fill:{flex:1},header:{flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:20,paddingTop:14,paddingBottom:10},brand:{fontSize:23,fontWeight:'800'},content:{padding:20,paddingBottom:32},row:{flexDirection:'row',alignItems:'center',gap:8,flexWrap:'wrap'},check:{width:44,height:44,borderWidth:2,borderRadius:14,alignItems:'center',justifyContent:'center'},tabs:{flexDirection:'row',borderTopWidth:1,padding:7,gap:3},tab:{flex:1,minHeight:48,borderRadius:12,alignItems:'center',justifyContent:'center'}});
