import React,{useState} from 'react';
import {View} from 'react-native';
import {Body,Button,Field,Choices,NumberField,DateField,TimeField} from './ui';
import type {TaskRecord} from './services/local-db';
const rules=require('../../../packages/core/src/mobile-rules');
export function TaskEditor({task,onSave}: {task:Partial<TaskRecord>;onSave:(task:any,steps:string[])=>Promise<void>}){
  const now=new Date(),date=rules.day(now);
  const [title,setTitle]=useState(task.title||''),[notes,setNotes]=useState(task.notes||''),[mode,setMode]=useState(['backlog','ongoing','day'].includes(task.scheduleMode||'')?task.scheduleMode!:'scheduled');
  const [planDate,setDate]=useState(task.dueAt?rules.day(task.dueAt):task.planDate||date),[time,setTime]=useState(task.dueAt?new Date(task.dueAt).toTimeString().slice(0,5):now.toTimeString().slice(0,5));
  const [priority,setPriority]=useState(task.priority||'normal'),[reminder,setReminder]=useState(task.reminderMode||'none'),[minutes,setMinutes]=useState(task.reminderMinutes||30);
  const [deadline,setDeadline]=useState(task.deadlineDate||''),[days,setDays]=useState(task.deadlineReminderDays??3),[estimate,setEstimate]=useState(task.estimateMinutes||25);
  const [repeat,setRepeat]=useState(task.recurrence?.kind||'none'),[category,setCategory]=useState(task.category||''),[steps,setSteps]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <View><Field label="这件事叫什么" value={title} onChange={setTitle}/><Choices label="推进方式" value={mode} onChange={setMode} options={[["scheduled","日期与时间"],["day","只安排日期"],["ongoing","每天推进"],["backlog","稍后分配"]]}/>{['scheduled','day'].includes(mode)&&<><DateField label="计划日期" value={planDate} optional={false} onChange={setDate}/>{mode==='scheduled'&&<TimeField label="执行时间" value={time} onChange={setTime}/>}</>}<Choices label="优先级" value={priority} onChange={setPriority} options={[["low","不着急"],["normal","普通"],["high","重要"]]}/><Choices label="提醒方式" value={reminder} onChange={setReminder} options={[["none","不单独提醒"],["event","提前提醒"],["interval","循环提醒"]]}/>{reminder!=='none'&&<NumberField label={reminder==='event'?'提前几分钟':'间隔几分钟'} value={minutes} onChange={setMinutes} max={10080}/>}<DateField label="最晚截止（可选）" value={deadline} onChange={setDeadline}/>{!!deadline&&<NumberField label="提前几天提醒截止" value={days} onChange={setDays} min={0} max={365}/>}<NumberField label="预计投入（分钟）" value={estimate} onChange={setEstimate} max={1440}/><Choices label="重复任务" value={repeat} onChange={setRepeat} options={[["none","不重复"],["daily","每天"],["weekdays","工作日"],["weekly","每周"],["monthly","每月"]]}/><Field label="分类（可选）" value={category} onChange={setCategory}/><Field label="备注" value={notes} onChange={setNotes} multiline/><Field label="添加小步骤（每行一项）" value={steps} onChange={setSteps} multiline/>{!!error&&<Body>{error}</Body>}<Button title={busy?'保存中…':task.id?'保存修改':'确认加入'} disabled={busy} onPress={()=>{setBusy(true);setError('');void (async()=>{const dueAt=mode==='scheduled'?new Date(`${planDate}T${time}:00`).toISOString():null;const value=rules.validateTaskDraft({...task,title,notes,scheduleMode:mode==='scheduled'?'fixed':mode,dueAt,planDate:['scheduled','day'].includes(mode)?planDate:null,priority,reminderMode:reminder,reminderMinutes:minutes,reminderActive:reminder!=='none',deadlineDate:deadline||null,deadlineReminderDays:days,estimateMinutes:estimate,category,recurrence:{kind:repeat,interval:1}});await onSave(value,steps.split('\n').map(x=>x.trim()).filter(Boolean));})().catch(e=>setError(e.message||String(e))).finally(()=>setBusy(false));}}/></View>;
}
export function HabitEditor({habit,onSave}: {habit:any;onSave:(h:any)=>Promise<void>}){
  const [title,setTitle]=useState(habit.title||''),[type,setType]=useState(habit.scheduleType||'interval'),[minutes,setMinutes]=useState(habit.intervalMinutes||60),[time,setTime]=useState(habit.time||'09:00'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <View><Field label="每天想坚持的小事" value={title} onChange={setTitle}/><Choices label="提醒节奏" value={type} onChange={setType} options={[["interval","每隔一段时间"],["daily","每天固定时间"]]}/>{type==='interval'?<NumberField label="间隔（分钟）" value={minutes} onChange={setMinutes} max={1440}/>:<TimeField label="每天几点" value={time} onChange={setTime}/>}<Body muted>循环提醒未处理时只保留一条；处理后从当前时间计算下一次。</Body>{!!error&&<Body>{error}</Body>}<Button title="保存每日坚持" disabled={busy} onPress={()=>{if(!title.trim()){setError('请填写名称');return;}setBusy(true);void onSave({...habit,title:title.trim(),scheduleType:type,intervalMinutes:minutes,time,active:habit.active!==false,icon:habit.icon||'✦'}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}/></View>;
}
