import React,{createContext,useContext,useState} from 'react';
import {Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View,KeyboardAvoidingView,Platform} from 'react-native';
import {getTheme,type ThemeTokens} from './theme/tokens';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
export const ThemeContext=createContext<ThemeTokens>(getTheme('bg1'));
export const useTheme=()=>useContext(ThemeContext);
export function Body({children,muted=false}: {children:React.ReactNode;muted?:boolean}){const t=useTheme();return <Text style={{color:muted?t.colors.muted:t.colors.ink,fontSize:16,lineHeight:24}}>{children}</Text>;}
export function Heading({children}: {children:React.ReactNode}){const t=useTheme();return <Text accessibilityRole="header" style={{color:t.colors.ink,fontSize:25,lineHeight:34,fontWeight:'800',marginBottom:12}}>{children}</Text>;}
export function Card({children}: {children:React.ReactNode}){const t=useTheme();return <View style={[s.card,{backgroundColor:t.colors.surface,borderColor:t.colors.border}]}>{children}</View>;}
export function Button({title,onPress,secondary=false,danger=false,disabled=false}: {title:string;onPress:()=>void;secondary?:boolean;danger?:boolean;disabled?:boolean}){const t=useTheme();return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,{backgroundColor:secondary?t.colors.canvas:t.colors.accent,borderColor:t.colors.border,opacity:disabled?0.55:pressed?0.8:1}]}><Text style={{fontSize:16,fontWeight:'800',color:danger?t.colors.danger:t.colors.ink,textAlign:'center'}}>{title}</Text></Pressable>;}
export function Field({label,value,onChange,placeholder='',numeric=false,multiline=false}: {label:string;value:string;onChange:(s:string)=>void;placeholder?:string;numeric?:boolean;multiline?:boolean}){const t=useTheme();return <View style={{marginBottom:12}}><Text style={{fontSize:15,color:t.colors.muted,marginBottom:6}}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={t.colors.muted} keyboardType={numeric?'number-pad':'default'} autoCapitalize="none" multiline={multiline} style={[s.input,{color:t.colors.ink,backgroundColor:t.colors.surface,borderColor:t.colors.border,minHeight:multiline?88:48}]} /></View>;}
export function Choices({label,options,value,onChange}: {label:string;options:readonly (readonly [string,string])[];value:string;onChange:(v:string)=>void}){const t=useTheme();return <View style={{marginBottom:14}}><Body muted>{label}</Body><View style={s.wrap}>{options.map(([id,name])=><Pressable accessibilityRole="radio" accessibilityState={{selected:value===id}} key={id} onPress={()=>onChange(id)} style={[s.choice,{backgroundColor:value===id?t.colors.accent:t.colors.surface,borderColor:t.colors.border}]}><Text style={{color:t.colors.ink,fontSize:15,fontWeight:value===id?'800':'500'}}>{name}</Text></Pressable>)}</View></View>;}
export function Sheet({visible,title,onClose,children}: {visible:boolean;title:string;onClose:()=>void;children:React.ReactNode}){const t=useTheme(),insets=useSafeAreaInsets();return <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.scrim}><View accessibilityViewIsModal style={[s.sheet,{backgroundColor:t.colors.canvas,paddingBottom:14+insets.bottom}]}><View style={s.headingRow}><Text style={{flex:1,color:t.colors.ink,fontSize:22,fontWeight:'800'}}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="关闭弹窗" onPress={onClose} style={s.close}><Text style={{fontSize:26,color:t.colors.ink}}>×</Text></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingBottom:24}}>{children}</ScrollView></View></KeyboardAvoidingView></Modal>;}
export function NumberField({label,value,onChange,min=1,max=180}: {label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number}){const t=useTheme();return <View style={{marginBottom:14}}><Body muted>{label}</Body><View style={s.number}><Button title="−" secondary disabled={value<=min} onPress={()=>onChange(Math.max(min,value-1))}/><TextInput accessibilityLabel={label} selectTextOnFocus keyboardType="number-pad" value={String(value)} onChangeText={v=>onChange(Math.max(min,Math.min(max,Number(v)||min)))} style={[s.input,{flex:1,textAlign:'center',color:t.colors.ink,borderColor:t.colors.border,backgroundColor:t.colors.surface}]}/><Button title="＋" secondary disabled={value>=max} onPress={()=>onChange(Math.min(max,value+1))}/></View></View>;}
export function DateField({label,value,onChange,optional=true}: {label:string;value:string;onChange:(v:string)=>void;optional?:boolean}){
  const t=useTheme(),[open,setOpen]=useState(false),[month,setMonth]=useState(new Date());
  const year=month.getFullYear(),m=month.getMonth(),days=new Date(year,m+1,0).getDate(),offset=(new Date(year,m,1).getDay()+6)%7;
  const iso=(y:number,mn:number,d:number)=>`${y}-${String(mn+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
  return <View style={{marginBottom:12}}><Body muted>{label}</Body><Button secondary title={value||'未设置'} onPress={()=>{setMonth(value?new Date(`${value}T12:00:00`):new Date());setOpen(true);}}/><Sheet visible={open} title={label} onClose={()=>setOpen(false)}><View style={s.number}><Button secondary title="‹" onPress={()=>setMonth(new Date(year,m-1,1))}/><Text style={{flex:1,textAlign:'center',color:t.colors.ink,fontSize:20,fontWeight:'800'}}>{year} 年 {m+1} 月</Text><Button secondary title="›" onPress={()=>setMonth(new Date(year,m+1,1))}/></View><View style={s.wrap}>{['一','二','三','四','五','六','日'].map(d=><Text key={d} style={{width:'13%',textAlign:'center',color:t.colors.muted,paddingVertical:8}}>{d}</Text>)}</View><View style={s.wrap}>{Array.from({length:offset+days},(_,i)=>i<offset?<View key={i} style={{width:'13%'}}/>:<Pressable key={i} accessibilityLabel={`${m+1}月${i-offset+1}日`} onPress={()=>{onChange(iso(year,m,i-offset+1));setOpen(false);}} style={{width:'13%',height:44,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:value===iso(year,m,i-offset+1)?t.colors.accent:t.colors.surface}}><Text style={{fontSize:17,color:t.colors.ink}}>{i-offset+1}</Text></Pressable>)}</View><Button title="今天" onPress={()=>{const n=new Date();onChange(iso(n.getFullYear(),n.getMonth(),n.getDate()));setOpen(false);}}/>{optional&&<Button secondary title="清除日期" onPress={()=>{onChange('');setOpen(false);}}/>}</Sheet></View>;
}
export function TimeField({label,value,onChange}: {label:string;value:string;onChange:(v:string)=>void}){
  const [open,setOpen]=useState(false),[hour,setHour]=useState('09'),[minute,setMinute]=useState('00'),[error,setError]=useState('');
  return <View style={{marginBottom:12}}><Body muted>{label}</Body><Button secondary title={value||'选择时间'} onPress={()=>{const [h,m]=value.split(':');setHour(h||'09');setMinute(m||'00');setError('');setOpen(true);}}/><Sheet visible={open} title={label} onClose={()=>setOpen(false)}><Field label="小时（0–23）" numeric value={hour} onChange={setHour}/><Field label="分钟（0–59）" numeric value={minute} onChange={setMinute}/>{!!error&&<Body>{error}</Body>}<Button secondary title="现在" onPress={()=>{const d=new Date();setHour(String(d.getHours()));setMinute(String(d.getMinutes()));}}/><Button title="确定" onPress={()=>{if(!/^\d{1,2}$/.test(hour)||!/^\d{1,2}$/.test(minute)||Number(hour)>23||Number(minute)>59){setError('请输入有效的 24 小时制时间');return;}onChange(`${hour.padStart(2,'0')}:${minute.padStart(2,'0')}`);setOpen(false);}}/></Sheet></View>;
}
export const s=StyleSheet.create({card:{borderWidth:1,borderRadius:20,padding:17,marginBottom:14},button:{borderWidth:1,borderRadius:14,minHeight:48,paddingHorizontal:16,paddingVertical:12,justifyContent:'center',marginVertical:4},input:{borderWidth:1,borderRadius:14,paddingHorizontal:14,paddingVertical:10,fontSize:17},wrap:{flexDirection:'row',flexWrap:'wrap',gap:3,marginTop:6},choice:{paddingHorizontal:13,paddingVertical:12,minHeight:44,borderWidth:1,borderRadius:12,marginRight:3,marginBottom:3},scrim:{flex:1,backgroundColor:'#20162B88',justifyContent:'flex-end'},sheet:{maxHeight:'94%',borderTopLeftRadius:26,borderTopRightRadius:26,padding:22,paddingBottom:14},headingRow:{flexDirection:'row',alignItems:'center',marginBottom:12},close:{width:48,height:48,alignItems:'center',justifyContent:'center'},number:{flexDirection:'row',alignItems:'center',gap:10}});
